### ISSUE TITLE
[Feature request]: Do my taxes

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#108]
### Whats the feature you would like to be added?

Weird I've never seen this CODE OF CONDUCT thing before. I didn't think it ever necessary to put how humans should treat other humans down into words. Heck that's what the founding documents of each country is for anyway. Have you read the ones for Germany? I bet the read very similar to the Constitution of the United States.

### Anything else you would like to add?

I'm concerned for you now because of that CODE OF CONDUCT, I'm wondering who has treated you so badly that it had to be stated.

Btw, you might lose reports because you require them to agree to it.

Instead it's better to say as a byline on the bottom of the forms that this project is governed by the CODE OF CONDUCT.

Also helpful resources wouldn't be more links regarding the code of conduct but instead a wiki explaining all the nuances of ServerPackCreator, both the webservice and the app.

![image](https://user-images.githubusercontent.com/3880072/143435249-d5f34b88-ec45-4f91-83a3-a0b6c68fe907.png)

It makes you look more political and stanced on the belief vs your own project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
> I'm concerned for you now because of that CODE OF CONDUCT, I'm wondering who has treated you so badly that it had to be stated.

This is more a way of protecting myself from harm and being able to handle people who misbehave by simply closing their issues should they break said code of conduct. By stating that this code of conduct exists, I can not be held responsible if someone else misbehaves, as they have been informed about it. In other words: It allows me to tell people to bugger off if they misbehave. Kinda like a preemptive mod-action..

**Comment by Griefed** [comment]
The helpful resources was added by GitHub itself. At least I didn't specify those resources anywhere.

**Comment by kreezxil** [comment]
I suggested reading about compounded contracts and similar. Probably ask a lawyer friend this?

"If I have a project on a service that has its own policy to protect its project holders, will my own protections get stronger if I add another policy on top of it? Or will the subsequent policy actually weaken the first one, and then that reciprocates back to the subsequent one, causing both policies to fall apart?"
