### ISSUE TITLE
Docs: Add the How-To page for macOS

### ISSUE THREAD

**Issue by whitebear60** [Griefed/ServerPackCreator#11]
I've created the How-To page for macOS users based on the standard Windows one. I don't know how to propose these changes in another way, so I've created this issue.

So, here is the text of this page: https://pastebin.com/u0qVb3ZG

**Comment by whitebear60** [comment]
Also, this page contains the fixed link to the `creator.conf` file in the Files table.

**Comment by Griefed** [comment]
Sweeeeeet, thank you so much!

**Comment by Griefed** [comment]
Your guide for macOS is available at [How-To macOS](https://github.com/Griefed/ServerPackCreator/wiki/Running-ServerPackCreator-on-MacOS)

Thank you very much for your contribution. If you'd like, you can add a line such as `macOS guide by [whitebear60](https://github.com/whitebear60)` to the How-To section of the README, create a pull request and then you'll be listed as a contributor to the repository.

Thanks again for taking the time out of your day to create a macOS guide. 

Cheers,
Griefed
