### ISSUE TITLE
[Feature request]: Java variable needed

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#118]
### Whats the feature you would like to be added?

The script needs a line for Java to use

Currently in the ".sh" we have

```bash
MINECRAFT="1.17.1"
FORGE="37.1.0"
ARGS=""
```

if we had one more for java
```bash
# default
JAVA="java"
```
Then for those of us with multiple javas to run multiple Minecrafts for example can easily change all the java in the script with just one variable.

### Anything else you would like to add?

this field doesn't need to be required.

![image](https://user-images.githubusercontent.com/3880072/144252014-bfcf7694-3bc9-4895-a810-9f940b8afc3e.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
You can just change the execution command at the end of the script. No need to make it more complex than it already is.

In the `start.sh` script for example, simple change
```sh
java $ARGS -jar forge.jar --nogui
``` 

to
```
/path/to/your/other_java/java $ARGS -jar forge.jar --nogui
```

**Comment by kreezxil** [comment]
since all the Linux distros I've used have sed, this to me is far better
way of doing it.

```bash
sed -i 's/java/"${JAVA}"/g' start.sh
sed -i 's/ARGS/ARGS\nJAVA="\/path\/to\/my\/other\/java"
```

**Comment by Griefed** [comment]
Will be available in the next alpha release. Dev build will be available [here ](https://git.griefed.de/Griefed/ServerPackCreator/-/jobs/4123) once it's finished building.

**Comment by Griefed** [comment]
Available as of [alpha.12](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.12).

Cheers,
Gtiefed
