### ISSUE TITLE
[Bug]: Unable to access jarfile fabric-server-launch.jar

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Griefed/ServerPackCreator#135]
### What happened?

I ran the Server Pack Creator with the following settings

![image](https://user-images.githubusercontent.com/17887664/145649707-66ddcc94-4e42-4296-a760-f72c76472dae.png)

Than ran the script.sh file and found the following error:
`Unable to access jarfile fabric-server-launch.jar`
I found the issue.  In the start.sh script (and the start.bat) I found:
`FABRIC="0.1.0.48"`
instead of
`FABRIC="0.12.11"`
When I made the change the server fired right up.
[install.log](https://github.com/Griefed/ServerPackCreator/files/7695788/install.log)

When I ran the script it asked me to accept the eula, which I did. However, the eula did not get written to a file until later when it was false. I had to stop the server > edit the eula > restart the server. I would be nice if the script wrote the eula file with true (as I answered in the terminal) instead of false.

### What did you expect to happen?

Detailed explanation on what you expected goes here!

### Version

3.0.0-alpha.11 (Alpha)

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya ClaudiusMinimus,

thanks for this report. Two for one, actually.

I'll take a look later today. 

Cheers,
Griefed

**Comment by Griefed** [comment]
Dev build .exe and .jar available at https://git.griefed.de/Griefed/ServerPackCreator/-/jobs/4109/artifacts/browse/build/libs/.

PLease test them and report back whether this fix works for you.

**Comment by Griefed** [comment]
Available as of [alpha.12](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.12).

Cheers,
Gtiefed
