### ISSUE TITLE
[Bug]: Typo in start.sh script

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Griefed/ServerPackCreator#152]
### What happened?

The script failed to start the server because it gave the following error:
`./start.sh: line 66: -Dlog4j2.formatMsgNoLookups=true: command not found`
I looked in the file script.sh and found:

`# SET JAVA="java"`
I changed it to the following and the script ran fine.
`JAVA="java"`

### What did you expect to happen?

n/a

### Version

3.0.0-alpha.12 (Alpha)

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Hi ClaudiusMinimus,

a fix is currently building and the corresponding alpha released after tests have been made.
I will post a comment when the build is available. Please give it a go then and see whether the issue is fixed for you.

Cheers,
Griefed

**Comment by Griefed** [comment]
Build artifacts for testing available at https://git.griefed.de/Griefed/ServerPackCreator/-/jobs/5164/artifacts/browse/build/libs/

Please give them a go and report back to me, whether this issue is fixed for you, @ClaudiusMinimus.

Cheers,
Griefed

**Comment by Griefed** [comment]
Lack of feedback leads me to assume the issue is now fixed or no longer relevant.

The fix will be available in the next alpha release.

Cheers,
Griefed
