### ISSUE TITLE
[Bug]: webservice [basically .13]

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#164]
### What happened?

The fabric 1.17.1 launcher needs **nogui** added to its end, or at lest an option disable the gui mode via the settings menu in which case this is a feature. but that option goes on the end and with no dashes.

### What did you expect to happen?

no gui to popup

### Version

3.0.0-alpha.12 (Alpha)

### Relevant log output

```shell
lol, i don't use the webservice in a browser.
```

### Anything else you would like to add?

```bash
echo "Starting server...";
echo "Minecraft version: $MINECRAFT";
echo "Fabric version: $FABRIC";
echo "Java args: $ARGS";

$JAVA $OTHERARGS $ARGS -jar fabric-server-launch.jar nogui
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Will be available in the upcoming alpha release, which has just been started.

**Comment by Griefed** [comment]
See [alpha.13](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.13)
