### ISSUE TITLE
[Bug]: Can't Start Server [Pack ver 2.4.2] Error: Could not find or load main class @user_jvm_args.txt 

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Griefed/ServerPackCreator#171]
### What happened?

A player wanting to set up a server posted this issue where he can't start the server. got this error:
> Error: Could not find or load main class @user_jvm_args.txt 

https://github.com/ClaudiusMinimus/Create_Potato_1.18.x/issues/1

### What did you expect to happen?

start.bat should have loaded user_jvm_args.txt 

### Version

3.0.0-alpha.13 (Alpha)

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Not a bug in ServerPackCreator.

Minecraft version 1.18.x requires Java 17. The mentioned error message 
```
Error: Could not find or load main class @user_jvm_args.txt
```
happens when you run the server with a Java installation that does not meet the requirement.

Source: https://minecraft.fandom.com/wiki/Java_Edition_1.18#:~:text=The%20game%20now%20requires%20Java%2017%20instead%20of%20Java%2016.
> General
> [...]
> - The game now requires Java 17 instead of Java 16.
> [...]

**Comment by ClaudiusMinimus** [comment]
Could you do a case check for Java 17 with 1.18.x servers and display a message to the user Java 17 is required?

**Comment by Griefed** [comment]
It is possible to check the version of the Java installation which gets used by the ARG/variable `java` in the script. 

However, that being said, it would open up the figurative can of worms of then having to check every Minecraft, Forge and Fabric versions manually first and compiling a list of which versions support which Java-versions, and *that* would *then* have to be continuously be maintained whenever a change in any version occurs.
The start scripts would also be bloated up with information pertaining to supported Java versions for Minecraft, Forge and Fabric versions, making it difficult for the average user to customize it to their liking for fear of breaking something.

It would have to be a system which would basically maintain itself, so to speak. To prevent as much manual work by the user as possible.

My feature-creep-sense is also tingling right now 😅 If I'm already checking for Java and Minecraft compatability, I might as well trigger the installation of the correct Java-version needed by the server. But then there are many different Linux distributions which handle package installation differently. And then there's Windows...

It's too much work for little benefit, and it's much easier to just tell any affected user which Java-version they need for any given server.

 Though a message saying something along the lines of 
> If you recieve the error message \"Error: Could not find or load main class @user_jvm_args.txt\" you may be using the wrong Java-version for this modded Minecraft server. Contact the modpack-developer or, if you made the server pack yourself, do a quick google-search for the used Minecraft version to find out which Java-version is required in order to run this server.

in the 1.18 scripts could at least lead people on the right track towards fixing any version mismatches.

I love the idea of automating this, don't get me wrong, but it would have to be done right and completely self-maintained, which I simply do not have the time for.

Hope this helps.

Cheers,
Griefed

**Comment by ClaudiusMinimus** [comment]
I can totally appreciate the nightmare this would open and I agree it should not be implemented. How about if they get the error is thrown, then display something like a generic checklist. For example:
> Something is wrong with your configuration. Check your settings, recommended Java version, [anything else you can think of]

Thank you for making this Server Creator application available!
CM

**Comment by ClaudiusMinimus** [comment]
I decided to manually add these files to the server installation.
[CURRENT_INSTALLER.txt](https://github.com/Griefed/ServerPackCreator/files/7834252/CURRENT_INSTALLER.txt)
[README.txt](https://github.com/Griefed/ServerPackCreator/files/7834253/README.txt)
It would be nice to have preselected files automatically added to the install zip.

**Comment by Griefed** [comment]
Considering the scripts already take care of what your README describes, and the Java 17 hint is a threeliner just as I mentioned above, I will not bloat up the server pack archive by adding more files.

**Comment by Griefed** [comment]
FYI: I've added the idea of shipping a bundled JRE with a server pack, as suggested by @Kreezxil, to Discussions 201 https://github.com/Griefed/ServerPackCreator/discussions/201
