### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Griefed/ServerPackCreator#172]
### What happened?

When I test a server installation I am always presented with this screen stating I need to agree to the EULA (see 1st image). I have tried both true and yes, however, after agreeing to the terms I am again presented with a message stating again I need to agree to the EULA (see 2nd image).

![image](https://user-images.githubusercontent.com/17887664/148664588-847a0190-86a0-4408-a225-7e49226afa9e.png)

![image](https://user-images.githubusercontent.com/17887664/148664603-ad0e2738-f0b2-45fd-82fd-fc57633a13b6.png)

When I open the EULA it reads `eula=false`

### What did you expect to happen?

It seems the Serverpack Creator should change `eula=false` to `eula=true`

### Version

3.0.0-alpha.13 (Alpha)

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Third line of the firdt screenshot, it says  that you need to type
> I agree
in order for the script to create the eula.txt 

Cheers,
Griefed

**Comment by ClaudiusMinimus** [comment]
Thank you for pointing out the missed instructions. Unfortunately, these instructions to type `I agree` two lines up were missed by several of my users and were missed by myself. I am not trying to be a pain, but I am attempting to help make your software easier to use. 

I would like to suggest the following changes.

Delete the line:
`"  ECHO Type \"I agree\" to indicate that you agree to Mojang's EULA.\n" +`

Change this line from:
`"  ECHO Do you agree to Mojang's EULA?\n" +`
To:
`"  ECHO If you agree to Mojang's EULA then type  \"I agree\" \n" +`

This simple change would be more concise, puts the prompt immediately in front of the user, and will likely reduce the risk of this issue ever coming up again.

Thank you,
CM

**Comment by Griefed** [comment]
>  I am not trying to be a pain

Hey, don't worry. I appreciate that people are opening issues for ServerPackCreator. It means someone is using it, which is awesome!

Whilst I am personally against this change, I have no solid argument against it, other than "Well, people should read the text that is printed on their monitors, then.", ​which is born more out of annoyance about some peoples inability to read their screen.

The information is right there, and yet people run and complain before doing the work and collecting and checking all the information they have first.

This is **not* directed at you. This happens to everyone, myself included. It just feels like it is happening more and more the older I get.

This change will be available in the next alpha release.

**Comment by Griefed** [comment]
See [alpha.14](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.14)

**Comment by ClaudiusMinimus** [comment]
Thank you very much for implementing this change! I greatly appreciate it! With hundreds of lines of logs flying it seems natural to focus on the last line. I truly believe this simple change will help many.

Thanks again for being open!
Have a great day!
CM

PS: I wish I could financially support you, but I am a retired and disabled grandpa on a fixed income. I hope others with means will help support you!

**Comment by Griefed** [comment]
> I wish I could financially support you, but I am a retired and disabled grandpa on a fixed income. I hope others with means will help support you!

Hey don't stress yourself! Reporting issues and making feature or change requests is already more than I could ask from anybody!

Take care of yourself, stay safe and stay awesome!

Cheers,
Griefed
