### ISSUE TITLE
[Bug]: Mods inside mod folder not copied to server pack even though mods-directory was specified

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#192]
### What happened?

creatd a server pack against my wod 2 pack. Noticed the server had loaded up and said it loaded 7 recipes. Checked to see if the mods had an issue, it copied no mods at all!

### What did you expect to happen?

to have the mods copy over.

### Version

3.0.0-alpha.15 (Alpha)

### Relevant log output

```shell
https://gist.github.com/kreezxil/8a3e1c6e0a850d0df747a211ca62d212
```

### Anything else you would like to add?

lol you don't need that version drop down because even you forget to put all the versions in it. 

![[]](https://i.imgur.com/bKoRnEq.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kreezxil** [comment]
looks like if there is a ,, in the list that causes a wildcard scenario and then nothing copies.

**Comment by kreezxil** [comment]
confirmed, that was what caused the mods to not copy over, a rogue ,, in the list of client mods.

**Comment by Griefed** [comment]
Heya Kreezxil,

> lol you don't need that version drop down because even you forget to put all the versions in it.
Yeah, I still need to figure out how to automatically write the new version into that field. Meh.

So was the error on your part, because you wronlgy configured SPC, or what?
Also, for future issues, please provide the logs from the `serverpackcreator.log` in the `logs` directory. The log panel in the GUI is a truncated one which, for example, does not list DEBUG entries and also omits the class from which the log entries got printed. The log panel is meant for adhoc debugging by the user only.

**Comment by Griefed** [comment]
Also, could you please send me a screenshot of the gui with your configuration, as well as your configuration file?

Btw. the GUI has a button, I believe I mentioned this before, for uploading the latest serverpackcreator.log 
![image](https://user-images.githubusercontent.com/44273438/150182156-9ea623af-c248-4199-bc7f-2d9c15ace021.png)

**Comment by kreezxil** [comment]
I explained what caused it. you can close this if that is what you want. I
personally would add a check to the code to remove empty fields.

**Comment by kreezxil** [comment]
by fields, i mean when the filename starts or ends with a space or is only
a space in a list.

**Comment by Griefed** [comment]
Aye, I've already added a TODO to the relevant lists to check for empty entries and to remove them from the config. Thanks for your feedback!

I'll close this issue. Feel free to open a new one if you encounter anything else. 😊

**Comment by Griefed** [comment]
Heya Kreezxil,

an improvement has emerged from this issue of yours.
The lazy people will be able to copy the whole modpack to the server pack directory if they so choose.
When I set the directoriesToCopy field to `config, , mods` it copied the whole modpack, and all files in it, to the server pack :D So I will be filtering `, ,` out of the list, but if someone specifies `copy_whole_modpack` and nothing else, the whole thing will be copied.

**Comment by kreezxil** [comment]
Mr. Burns thanks you.
https://c.tenor.com/eEQMloOHSG0AAAAC/simpsons-mr-burns.gif
