### ISSUE TITLE
[Feature request]: Bundle Adoptium Java

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#199]
### Whats the feature you would like to be added?

Because modpacks need one of the either Java 8, 16, or 17, it would be nice to have the corresponding https://adoptium.net java prebundled with the server pack. This would prevent issues as reported by Jelaw#7138 from happening as seen in this report: https://gist.github.com/242b365e186044693027dddaf6168b1b

### Anything else you would like to add?

I wouldn't consider this a front burner feature, but it would be nice to have.

At a minimum, the pack creator could specify which java to use. And then the start script could try to detect the target system's java versions and select the matching one, if one doesn't exist, it would just download the right one from Adoptium.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Similar discussion was already had here: https://github.com/Griefed/ServerPackCreator/issues/171#issuecomment-1008081607

I won't prebundle JREs or JDKs, sorry.

**Comment by Griefed** [comment]
I expect users to know what Java version they need for their servers. This is exactly the reason why the Java variable in the scripts exists in the first place.

**Comment by kreezxil** [comment]
did you read the rest of it before reacting? i mentioned an autodection system that would get the target java if it were missing. that would cause an issue with curseforge.

**Comment by Griefed** [comment]
Copy pasta from Discord to make sure the conversation doesn't disappear into the aether.

>I did.
>However, the arguments from https://github.com/Griefed/ServerPackCreator/issues/171#issuecomment-1008081607 still >apply. I would have to write and maintain a system where ServerPackCreator keeps a list of all Minecraft, Forge or Fabric >versions and their compatible JREs or JDKs. Said list would, ideally, be self maintained. 
>The autodetection system would have to be written, too. I simply do not have time for that, unfortunately. This also goes >above and beyond creating a server pack, as this would ship the entire environment needed to run a server pack, too. I >consider this feature creep.
>
>It's a can of worms I can not open, sorry.
>Don't get me wrong, I like the idea, but it is out of reach for me and would be better suited for an addon.

>>do you have a detail explanation on how to make addons?

>The fabled Addon System™ (which I still haven't gotten around to improving sadface ). An example is available here: >https://github.com/Griefed/ServerPackCreatorExampleAddon
>It basically, very shoddily, passes the configuration as command line arguments. It#s the best I could come up with at the >time, about three or four months ago.
>
>The goal is to have a system where the configuration for a server pack gets passed to all addons. Said addons can then do >whatever they want.
>
>The current addon "interface", if you can call it that, hasn't been updated in ages. So the passed configuration is >incomplete and any current addon won't receive all values.
>
>You could, in theory, go ahead and write the logic which does what you described in your feature request already. Though >please be aware that the entrypoint will change at some point due to me reworking the addon system.
>ServerPackCreator will offer various points at which addon execution will occur.
>1. After the creation of a server pack, but *before the zip-archive creation
>2. After zip-archive creation (so you have one archive for, say, CurseForge, one for personal use)
>3. Adding tabbed panes in the gui which can then hold their own logic 
>I realize this is probably not a satisfying answer. Sorry.
>
>Another nice idea would be to then have an addon which uploads the newly generated server pack, with the bundled >JRE/JDK to a server. Any combination of addons could, in theory, result in an automated system where the user would only >need to configure SPC once, and all the rest is then done for them. From creating the server pack, to creating a working >environment, and then updating a server.


Love you, @kreezxil, but unfortunately I can not realize this request for you. 😥

**Comment by Griefed** [comment]
I went ahead and added your idea to Discussion 201 https://github.com/Griefed/ServerPackCreator/discussions/201 so it doesn't get lost in the aether. If you have anything else to add, feel free to talk about it in the mentioned discussion thread.
