### ISSUE TITLE
[Improvement request]: Updated # List of client-only mods to delete from serverpack.

### ISSUE THREAD

**Issue by TheButterbrotMan** [Griefed/ServerPackCreator#200]
clientMods = ["AdvancementPlaques-","medievalmusic-","3dSkinLayers-","AmbientSounds_","backtools-","BetterAdvancements-","BetterAnimationsCollection-","BetterDarkMode-","betterf3-","BetterF3-","BetterFoliage-","BetterPingDisplay-","BetterPlacement-","Blur-","catalogue-","cherishedworlds-","classicbar-","clickadv-","ClientTweaks_","configured-","Controlling-","CraftPresence-","CTM-","customdiscordrpc-","CustomMainMenu-","defaultoptions-","DefaultOptions_","desiredservers-","Ding-","drippyloadingscreen-","drippyloadingscreen_","Durability101-","dynmus-","dynamic-music-","DynamicSurroundings-","DynamicSurroundingsHuds-","eiramoticons-","EiraMoticons_","EnchantmentDescriptions-","EquipmentCompare-","extremesoundmuffler-","extremeSoundMuffler-","Fallingleaves-","fallingleaves-","fancymenu_","findme-","flickerfix-","FpsReducer-","FullscreenWindowed-","WindowedFullscreen-","InventoryEssentials_","InventorySpam-","invtweaks-","InventoryTweaks-","ItemBorders-","itemzoom","itlt-","jeed-","jeiintegration_","JustEnoughProfessions-","JEITweaker-","justenoughbeacons-","JustEnoughCalculation-","jehc-","just-enough-harvestcraft-","JustEnoughProfessions-","JustEnoughResources-","keywizard-","konkrete_","lazydfu-","LegendaryTooltips-","LightOverlay-","light-overlay-","LLOverlayReloaded-","loadmyresources_","lootbeams-","mcbindtype-","modnametooltip_","modnametooltip-","moreoverlays-","MouseTweaks-","multihotbar-","MyServerIsCompatible-","Neat","NotifMod-","OldJavaWarning-","ornaments-","armorchroma-","overloadedarmorbar-","PackMenu-","PickUpNotifier-","Ping-","preciseblockplacing-","presencefootsteps-","PresenceFootsteps-","ReAuth-","ResourceLoader-","shutupexperimentalsettings-","SimpleDiscordRichPresence-","smoothboot-","sounddeviceoptions-","SpawnerFix-","spoticraft-","tconplanner-","timestamps-","Tips-","TipTheScales-","Toast Control-","Toast-Control-","torohealth-","toughnessbar-","TravelersTitles-","WorldNameRandomizer-"]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Thanks for opening this improvement request. I will add any missing mods to the fallback list. :)

**Comment by Griefed** [comment]
Expanded fallback clientside modslist with 3dSkinLayers-, armorchroma-, Craftpresence-, medievalmusic- and MyServerIsCompatible-

Thanks!
