### ISSUE TITLE
[Improvement]: Simplify Fabric server packs by migrating to new launcher completely (needs testing)

### ISSUE THREAD

**Issue by TheButterbrotMan** [Griefed/ServerPackCreator#202]
### What happened?

I did generate my serverpack, and it seems like on fabric server.jar and libraries are still included.

### What did you expect to happen?

I thougth cuz you use the new fabric-server-launcher, both of them will be obsolete.

### Version

3.0.0-alpha.13

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**EDIT BY GRIEFED:**
Thorough testing of as many Fabric and Minecraft versions as possible is required. If the new and improved Fabric launcher is indeed available for all Fabric versions, and therefore for all Minecraft versions for which Fabric exists, this would simplify Fabric server packs immensely. Needs thorough testing, though.

**Comment by TheButterbrotMan** [comment]
`#!/usr/bin/env bash
# Start script generated by ServerPackCreator.
# This script checks for the Minecraft and Forge JAR-Files, and if they are not found, they are downloaded and installed.
# If everything is in order, the server is started.

JAVA="java"
MINECRAFT="1.18.1"
FABRIC="0.12.12"
INSTALLER="0.10.2"
ARGS=""
OTHERARGS="-Dlog4j2.formatMsgNoLookups=true"

if [[ ! -s "fabric-server-launch.jar" ]];then

  echo "Fabric Server JAR-file not found. Downloading installer...";
  wget -O fabric-installer.jar https://maven.fabricmc.net/net/fabricmc/fabric-installer/$INSTALLER/fabric-installer-$INSTALLER.jar;

  if [[ -s "fabric-installer.jar" ]];then

    echo "Installer downloaded. Installing...";
    java -jar fabric-installer.jar server -mcversion $MINECRAFT -loader $FABRIC -downloadMinecraft;

    if [[ -s "fabric-server-launch.jar" ]];then
      rm -rf .fabric-installer;
      rm -f fabric-installer.jar;
      echo "Installation complete. fabric-installer.jar deleted.";
    fi

  else
    echo "fabric-installer.jar not found. Maybe the Fabric server are having trouble.";
    echo "Please try again in a couple of minutes.";
  fi
else
  echo "fabric-server-launch.jar present. Moving on...";
fi

if [[ ! -s "server.jar" ]];then
  echo "Minecraft Server JAR-file not found. Downloading...";
  wget -O server.jar https://launcher.mojang.com/v1/objects/125e5adf40c659fd3bce3e66e67a16bb49ecc1b9/server.jar;
else
  echo "server.jar present. Moving on...";
fi

if [[ ! -s "eula.txt" ]];then
  echo "Mojang's EULA has not yet been accepted. In order to run a Minecraft server, you must accept Mojang's EULA."
  echo "Mojang's EULA is available to read at https://account.mojang.com/documents/minecraft_eula"
  echo "If you agree to Mojang's EULA then type 'I agree'"
  read ANSWER
  if [[ "$ANSWER" = "I agree" ]]; then
    echo "User agreed to Mojang's EULA."
    echo "#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula)." > eula.txt;
    echo "eula=true" >> eula.txt;
  else
    echo "User did not agree to Mojang's EULA."
  fi
else
  echo "eula.txt present. Moving on...";
fi

echo "Starting server...";
echo "Minecraft version: $MINECRAFT";
echo "Fabric version: $FABRIC";
echo "Java version:"
$JAVA --version
echo "Java args: $ARGS";

$JAVA $OTHERARGS $ARGS -jar fabric-server-launch.jar nogui`

**Comment by Griefed** [comment]
Heya TheButterbrotMan,

ich habe die libraries und server.jar Dateien bewusst nicht angefasst. Stattdessen geht ServerPackCreator hin und tauscht die `fabric-server-launch.jar`, welche der Fabric Installer erstellt, mit der von dir genannten Fabric Server Launcher JAR aus. 
Soweit ich das sehen konnte gibt es diese verbesserte Launcher JAR aber nicht für alle Minecraft/Fabric Versionen, also tauscht SPC nur, wenn die JAR erfolgreich gedownloaded wurde.

Mit Fabric Servern kenne ich mich nicht besonders gut aus. Nur das nötigste quasi, um server packs generieren zu können. 😅
Kannst du bestätigen, dass die libraries und die server.jar definitiv **NICHT** mehr benötigt werden, wenn die neue Launcher JAR vorhanden ist?

Cheers,
Griefed

**Comment by TheButterbrotMan** [comment]
![image](https://user-images.githubusercontent.com/64548098/150697393-57c11a49-9555-4f71-8249-931f1f60b500.png)

**Comment by Griefed** [comment]
?

**Comment by TheButterbrotMan** [comment]
> ![image](https://user-images.githubusercontent.com/64548098/150697393-57c11a49-9555-4f71-8249-931f1f60b500.png)

Ich kann definitiv bestätigen das dies alles was nötig ist ist, um einen Fabric-Server zu starten.

**Comment by Griefed** [comment]
> Ich kann definitiv bestätigen das dies alles was nötig ist ist, um einen Fabric-Server zu starten.

Kay, dann kann ich die Dateien löschen, sofern der bessere Launcher erfolgreich gedownloaded wurde.
Bei den Skripten wirds nochmal komplizierter....da muss ich mir was einfallen lassen wie ich das mache...

**Comment by TheButterbrotMan** [comment]
Außerdem scheint anscheinend etwas mit deiner fabric-server-launch.jar nicht zu stimmen, wenn ich versuche diese zu starten passiert nichts, die original generiert alle nötigen Dateien.

**Comment by Griefed** [comment]
> EDIT: Ich teste es grade nocheimal.

Ich auch. Das wundert mich grad. Schaumermal. ☕

**Comment by TheButterbrotMan** [comment]
> > EDIT: Ich teste es grade nocheimal.
> 
> Ich auch. Das wundert mich grad. Schaumermal. ☕

Wahr wohl falscher Alarm, funktioniert alles wie gehabt. :)

**Comment by Griefed** [comment]
Ich schaue es mir trotzdem lieber nochmal an 😂

**Comment by Griefed** [comment]
```
2022-01-23T21:54:02,296  INFO [pool-2-thread-1] (ServerPackHandler.java:324) - Replacing fabric-server-launch.jar with improved Fabric Server Launcher.
2022-01-23T21:54:02,296 DEBUG [pool-2-thread-1] (ServerPackHandler.java:328) - File replaced.
```

Das passt soweit.

Was interessant ist, ist dass der neue Launcher eine andere Datei-Struktur erzeugt. Fabric ist in der Hinsicht grad sehr verwirrend....wtf Fabric

Neuer Launcher:
- `libraries` wird erstellt
- server.jar wird **nicht** erstellt
    - Stattdessen wird `versions/1.18.1/server-1.18.1.jar` erstellt....?! Das ist ungünstig. Das darf nicht mit in dem von ServerPackCreator erstellten ZIP-Archiv landen. Sonst kann ich oder ein Nutzer in Schwierigkeiten geraten. Mojang's TOS und EULA etc.
- Löscht man `libraries`, `server.jar` und `versions`(sofern versions vorhanden ist), installiert der Launcher den Minecraft Server und die libraries komplett neu, wodurch `server.jar` **DANN** ungenutzt bleibt, obwohl die Skripte diese downloaden.

Alter Launcher:
- Erstellt `libraries` und `server.jar`
- Startet man über die Skripte, werden `libraries` und `server.jar` verwendet. Alles gut soweit.
- Löscht man `libraries` und startet über die Skripte: `Error: Could not find or load main class net.fabricmc.loader.impl.launch.server.FabricServerLauncher
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.server.FabricServerLauncher`
- Löscht man fabric-server-launch.jar, sodass die Skripte die Installation von Fabric durchführen, wird die Struktur vom neuen Launcher verwendet


Frage meinerseits an dieser Stelle: WER DENKT SICH SOWAS AUS xD

**Comment by TheButterbrotMan** [comment]
> ```
> 2022-01-23T21:54:02,296  INFO [pool-2-thread-1] (ServerPackHandler.java:324) - Replacing fabric-server-launch.jar with improved Fabric Server Launcher.
> 2022-01-23T21:54:02,296 DEBUG [pool-2-thread-1] (ServerPackHandler.java:328) - File replaced.
> ```
> 
> Das passt soweit.
> 
> Was interessant ist, ist dass der neue Launcher eine andere Datei-Struktur erzeugt. Fabric ist in der Hinsicht grad sehr verwirrend....wtf Fabric
> 
> Neuer Launcher:
> 
> * `libraries` wird erstellt
> * server.jar wird **nicht** erstellt
>   
>   * Stattdessen wird `versions/1.18.1/server-1.18.1.jar` erstellt....?! Das ist ungünstig. Das darf nicht mit in dem von ServerPackCreator erstellten ZIP-Archiv landen. Sonst kann ich oder ein Nutzer in Schwierigkeiten geraten. Mojang's TOS und EULA etc.
> * Löscht man `libraries`, `server.jar` und `versions`(sofern versions vorhanden ist), installiert der Launcher den Minecraft Server und die libraries komplett neu, wodurch `server.jar` **DANN** ungenutzt bleibt, obwohl die Skripte diese downloaden.
> 
> Alter Launcher:
> 
> * Erstellt `libraries` und `server.jar`
> * Startet man über die Skripte, werden `libraries` und `server.jar` verwendet. Alles gut soweit.
> * Löscht man `libraries` und startet über die Skripte: `Error: Could not find or load main class net.fabricmc.loader.impl.launch.server.FabricServerLauncher Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.launch.server.FabricServerLauncher`
> * Löscht man fabric-server-launch.jar, sodass die Skripte die Installation von Fabric durchführen, wird die Struktur vom neuen Launcher verwendet
> 
> Frage meinerseits an dieser Stelle: WER DENKT SICH SOWAS AUS xD

Also im Prinzip musste du in der Fabricversion echt nur den "Improved Launcher" reinschieben, das ist alles. Dann funktioniert es. Ich würde empfehlen diese Variante zu verwenden, macht das Serverpack kleiner, lässt sich besser und schneller auf nen gemieten schieben.

**Comment by Griefed** [comment]
Problem ist halt nur dass das alles davon abhängig ist, dass es den Improved Launcher für die spezifizierte Minecraft und Fabric Version gibt.

**Comment by TheButterbrotMan** [comment]
Ich dachte immer der wäre schon immer so gewesen.

**Comment by TheButterbrotMan** [comment]
Also, fabric für die 1.13 gibt es ja nicht, hat ja erst mit 1.14 angefangen. Ich habs jetzt nicht getestet, aber es sieht so aus als hätten alle diese Versionen diesen Launcher inbegriffen?

**Comment by TheButterbrotMan** [comment]
Grade getestet, sieht nicht nur so aus, selbst die erste Fabricversion tut dies.

**Comment by Griefed** [comment]
Die metadata und indexes sind nicht die informativsten. Da hat Forge wiederrum die Nase vorn. Bei Forge kann man sich z.B. wundervoll eine Liste aller Unterstützden Minecraft Versionen für eine Forge Version ansehen:
```JSON
  "1.18": [
    "1.18-38.0.0",
    "1.18-38.0.1",
    "1.18-38.0.2",
    "1.18-38.0.3",
    "1.18-38.0.4",
    "1.18-38.0.5",
    "1.18-38.0.6",
    "1.18-38.0.8",
    "1.18-38.0.10",
    "1.18-38.0.11",
    "1.18-38.0.12",
    "1.18-38.0.13",
    "1.18-38.0.14",
    "1.18-38.0.15",
    "1.18-38.0.16",
    "1.18-38.0.17"
  ],
```

Währenddessen bei Fabric:
```xml
<metadata>
  <groupId>net.fabricmc</groupId>
  <artifactId>fabric-loader</artifactId>
  <versioning>
    <latest>0.12.12</latest>
    <release>0.12.12</release>
    <versions>
      <version>0.1.0.48</version>
      <version>0.1.0.49</version>
      <version>0.1.0.50</version>
      <version>0.1.0.51</version>
      <version>0.1.0.52</version>
      <version>0.2.0.53</version>
      [...]
```

```xml
<metadata>
  <groupId>net.fabricmc</groupId>
  <artifactId>fabric-installer</artifactId>
  <versioning>
    <latest>0.10.2</latest>
    <release>0.10.2</release>
    <versions>
      <version>0.2.0.7</version>
      <version>0.2.1.8</version>
      <version>0.2.1.9</version>
      [...]
```

Muss ich mir mal genauer anschauen...

**Comment by Griefed** [comment]
>Also, fabric für die 1.13 gibt es ja nicht, hat ja erst mit 1.14 angefangen. Ich habs jetzt nicht getestet, aber es sieht so aus als hätten alle diese Versionen diesen Launcher inbegriffen?
> Grade getestet, sieht nicht nur so aus, selbst die erste Fabricversion tut dies.

Wenn dem so ist, und das muss gründlich getestet werden, würde das server packs für Fabric vereinfachen. Skripte würden simpler ausfallen, und Archive würden kleiner werden.

**Comment by TheButterbrotMan** [comment]
https://fabricmc.net/use/server/

Kannst die runterladen, starten und der Server wird da sein, egal welche Version.

**Comment by Griefed** [comment]
Dem scheint wirklich so zu sein. Wenn ich mal durch `https://meta.fabricmc.net/v2/versions/loader/<Minecraft_Version>/<Fabric_Version>` durch-curle, sieht das gut aus.

Okay, das bedeutet:
- Server installation bei Fabric würde damit komplett rausfallen
- Der Fabric Installer ist in ServerPackCreator komplett durch den neuen Launcher zu ersetzen
- GUI, Hilfen, etc. müssen dahingehen aktualisiert werden, dass Benutzer darüber informiert werden, dass die Server Installation nur noch für Forge relevant ist
Viel Refactoring...

**Comment by Griefed** [comment]
Jetzt musst du als Fabric Experte mal helfen. Ich hab auf dem Favric Discord nachgefragt, ob es Versionen gobt die der Launcher nicht unterstützt.
Antwort:
> it only works with newer fabric loader versions
> fabric loader however is cross version, so unless there is a mod incompatibility (which usually involves the mod being broken / using non-api internals) there is no good reason to use anything but the latest
> i.e. latest loader on any mc version works with the new server launcher
> The website only shows compatible versions, installer 0.8.0 or higher, loader 0.12.0 or higher, all minecraft versions.

Kannst du bestätigen, dass der Fabric Loader Versionsübergreifend funktioniert, also bei Mods?

**Comment by TheButterbrotMan** [comment]
Ich habe noch dreimal feststellen können das ein Mod aufgrund der Version des falschen Loaders nicht funktioniert hat, weil der Autor die Fabricversion gehardcodet hatte. Das hat er aber sofort behoben, und der Mod lief.

Es gibt also sehr wohl hardgecodete Fabricversionen, (which usually involves the mod being broken / using non-api internals), da hat er absolut recht.

**Comment by Griefed** [comment]
In dem Fall kann durchaus der neue Launcher verwendet werden und die Installation, so wie sie derzeit existiert, für Fabric komplett wegfallen.

Das macht die Änderungen der Fabric Skripte entsprechend angenehmer. Ich hatte mir grad schon mal aufgezeichnet, was der Worst Case wäre bei den Skripten. Wär nicht schön geworden. Von daher bin ich froh dass ich mir da sehr viel Zeit und Arbeit sparen kann.

Dann gibt es folgendes für mich zu tun:
1. Fabric Server Installation entfernen
2. Fabric Skripte an den neuen Launcher anpassen
     2.1 Eine Warnung in die Konsole ausgeben, dass wenn eine Mod nicht mit der aktuellsten Fabric Version kompatibel ist der Entwickler der Mod darüber informiert werden muss und dass dies KEIN ServerPackCreator Problem ist
3. Bei Fabric Modpacks die spezifizierung der Version entfernen, da automatisch die aktuellste Version verwendet werden soll
4. SERVER_PACK_INFO.txt zum Fabric modpack hinzufügen, welche auch nochmal auf 2.1 Hinweist

Mir grauts nur vor den Meldungen die dann aufkommen werden, dass server packs auf einmal nicht mehr funktionieren, weil eine Mod mit drin war, die die Version festgeschrieben hatte....da hab ich ja mal so gar keinen Bock drauf. 😅

**Comment by TheButterbrotMan** [comment]
Fabric zeigt das dann auch an, wenn die falsche Version benutzt wird. Also ABC ist nur mit 0.12.11 kompatibel.

**Comment by Griefed** [comment]
> Jemand der sich dann bei dir beschwert, muss nicht lesen können...xD

Schon gehabt....

**Comment by Griefed** [comment]
Gut, bei der ganzen Thematik handelt es sich insgesamt aber dennoch um viel refaktorierung, Löschung und Ummodellierung von Code, weshalb das erstmal hinten angestellt werden wird. Die Fabric server packs als solche funktionieren ja. Der mehrwert durch den neuen Launcher ist meines erachtens nicht so drastisch groß, dass es rechtfertigt die Änderung noch in 3.0 zu schieben.

Für den Moment haben werden wir also "Das beste aus beiden Welten" haben:
1. Ein Fabric server pack wird, sofern möglich, den neuen verbesserten Fabric Server Launcher haben
    1.1 Wenn der bessere Launcher mit dabei ist, dann gibt es auch eine kleine SERVER_PACK_INFO.txt Datei. Inhalt weiter unten
    1.2 Es werden BEIDE launcher zur Verfügung gestellt, sofern möglich. Der alte wird nicht ausgetauscht. Es wird lediglich der neue mit hinzugepackt, wenn er denn für die spezifizierte Fabric Version existiert.
2. ZIP-Archive werden weiterhin `libraries` beinhalten, da ohne diese die alte Methode, über `fabric-server-launch.jar` auf Managed Servers nicht funktionieren würde.
    2.1 Auf unmanaged, also Servern mit Shell-Zugriff, könnten die `libraries` und der `fabric-server-launch.jar` weggelassen werden, da die Skripte dann dafür sorgen dass alles wieder da ist. Da ein Archiv aber eher an Leute verteilt wird die wenig Ahnung von Servern haben, handelt es sich in der Regel eher um Managed Servers, oder Leute die einfach nur ein Skript ausführen wollen um glücklich zu sein. Also: Bleibt erstmal alles drin. Die 40MB machen bei z.B. deinem 1GB Monster eines server packs den Kohl auch nicht mehr fett.
3. Dadurch dass beide Launcher, die Libraries etc. alles da ist, werden so auch die Modpacks bedient, die Mods enthalten welche vielleicht nicht mit der aktuellsten Fabric Version kompatibel sind. Namentlich Mods die vielleicht nicht mehr aktiv entwickelt werden, wo so schnell auch nichts gefixt werden kann. Sehe ich als Vorteil


SERVER_PACK_INFO.txt
>If you are using this server pack on a managed server, meaning you can not execute scripts, please use the fabric-server-launcher.jar instead of the fabric-server-launch.jar. Note the extra "er" at the end of "launcher".
>This is the improved Fabric Server Launcher, which will take care of downloading and installing the Minecraft server and any and all libraries needed for running the Fabric server.
>
>The downside of this method is the occasional incompatibility of mods with the Fabric version, as the new Fabric Server Launcher always uses the latest available Fabric version.
>If a mod is incompatible with said latest Fabric version, contact the mod-author and ask them to remedy the situation.
>The official Fabric Discord had the following to add to this:
>    Fabric loader however is cross version, so unless there is a mod incompatibility (which usually involves the mod being broken / using non-api internals)
>    there is no good reason to use anything but the latest. I.e. the latest loader on any Minecraft version works with the new server launcher.

**Comment by Griefed** [comment]
There's been an update regaring this issue.

Fabric scripts going forward will check for existence of the improved Fabric server launcher and use that one if it exists. Otherwise, the regular server checks/installation will occur, as they have been for quite some time now.

This renders this ticket effectively resolved. It's the best realistic solution to this issue. The improved server launcher may not be available for older versions and I would prefer ServerPackCreator to be able to support older versions, on the off-chance someone, somewhere, stumbles upon an old, deserted modpack, which runs in an old version.

This issue will be closed once the next full release has been published. :)

Enjoy! Cheers,

Griefed
