### ISSUE TITLE
[Documentation]: because of the MOTHER OF CHANGELOGS

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#239]
### Which documentation would you like to be updated?

It's been a long time since you updated your WIKI. From the looks of this changelog, I think you need to update it again before it gets out of hand.

https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-beta.1

### Anything else you would like to add?

Tell me! woo hoo! I got a new monitor! Check it out!

![image](https://user-images.githubusercontent.com/3880072/153589698-ebb7b8c1-3e12-440a-938c-c137875384e3.png)

> AOC C32G2 32" Curved Frameless Gaming Monitor FHD, 1500R Curved VA, 1ms, 165Hz, FreeSync, Height adjustable, 3-Year Zero Dead Pixel Policy, Black
https://www.amazon.com/gp/product/B08BT9DZQW/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Good point with the Wiki :D Thanks.

Also nice new monitor! Out of curiosity, why didn't you go for the 32" QHD one?

**Comment by Griefed** [comment]
There was no Changelog page for ServerPackCreator. There is now: [SPC Changelog](https://wiki.griefed.de/en/Documentation/ServerPackCreator/Changelog)

**Comment by Griefed** [comment]
Wiki page created and changelog condensed. I'm closing this issue. 🙂

Don't hesitate to open a new issue if you encounter anything else.

Cheers,
Griefed
