### ISSUE TITLE
[Bug]: start.sh, minor bug --version

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#274]
### What happened?

at the bottom of the script you have **java --version**, however that generate cosmetic error on start, the correct writing is **java -version**

using 3.0.0.beta.4, will test .7 in moment.

### What did you expect to happen?

not print error lines

### Version

3.0.0.beta.4

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Kreexzil,

thanks for reporting this issue.

> using 3.0.0.beta.4, will test .7 in moment.

This is most likey still the case in beta.7, as I haven't touched the start scripts in a while.
I'll take a look.

Cheers,
Griefed

**Comment by Griefed** [comment]
Fix available in [beta.8 ](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-beta.8) 🙂
