### ISSUE TITLE
[Improvement request]: Add new Clientsidemods

### ISSUE THREAD

**Issue by TheButterbrotMan** [Griefed/ServerPackCreator#317]
### Whats the feature you would like to be improved?

https://www.curseforge.com/minecraft/mc-mods/charmonium
https://www.curseforge.com/minecraft/mc-mods/dashloader
https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya TheButterbrotMan,

thanks for this these mods. I'll add them to the fallback list. The new fallback list will be available in the next version.

Cheers,
Griefed

**Comment by TheButterbrotMan** [comment]
https://www.curseforge.com/minecraft/mc-mods/creativecore is client & serverside!

**Comment by Griefed** [comment]
I had a suspicion about CreativeCore being required on both sides. I remember seing something like that as a result of the ServerPackCreator sideness scanning and seeing a server mod somewhere, which used CreativeCore as a library. Thanks!

**Comment by Griefed** [comment]
Fallbacklist updated in commit https://github.com/Griefed/ServerPackCreator/commit/2dab9ade4f6f87bd2369f8fdf72121c8ec985b80

If you have additional mods you would like to be added to the fallback list, do not hesitate to open another improvement request.

Until then! Cheers,
Griefed
