### ISSUE TITLE
[Improvement request]: More compatibilites

### ISSUE THREAD

**Issue by TheButterbrotMan** [Griefed/ServerPackCreator#318]
### Whats the feature you would like to be improved?

https://www.curseforge.com/minecraft/mc-mods/keymap
https://www.curseforge.com/minecraft/mc-mods/music-duration-reducer
https://www.curseforge.com/minecraft/mc-mods/armorpoints
https://www.curseforge.com/minecraft/mc-mods/fabric-emotes
https://www.curseforge.com/minecraft/mc-mods/ngrok-lan
https://www.curseforge.com/minecraft/mc-mods/ambient-environment
https://www.curseforge.com/minecraft/mc-mods/ambientsounds
https://www.curseforge.com/minecraft/mc-mods/antighost
https://www.curseforge.com/minecraft/mc-mods/armor-sound-tweak
https://www.curseforge.com/minecraft/mc-mods/auth-me
https://www.curseforge.com/minecraft/mc-mods/autoreconnect
https://www.curseforge.com/minecraft/mc-mods/axolotl-bucket-fix
https://www.curseforge.com/minecraft/mc-mods/better-taskbar
https://www.curseforge.com/minecraft/mc-mods/betterf3
https://www.curseforge.com/minecraft/mc-mods/bisecthosting-server-integration-menu-fabric
https://www.curseforge.com/minecraft/mc-mods/blur-fabric
https://www.curseforge.com/minecraft/mc-mods/borderless-mining
https://www.curseforge.com/minecraft/mc-mods/chat-heads
https://www.curseforge.com/minecraft/mc-mods/craftpresence
https://www.curseforge.com/minecraft/mc-mods/cull-leaves
https://www.curseforge.com/minecraft/mc-mods/delete-worlds-to-trash-fabric
https://www.curseforge.com/minecraft/mc-mods/dripsounds-fabric

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya TheButterbrotMan,

thanks for these mods! 
Although a couple of these are already in the [fallback list](https://github.com/Griefed/ServerPackCreator/blob/main/backend/main/java/de/griefed/serverpackcreator/ApplicationProperties.java#L51), so no need to add them. Namely:

- `AmbientSounds_`
- `BetterF3-`
- `bhmenu-` & `BH-Menu-`
- `CraftPresence`

I'll check every other entry and add them to the fallback list. Thanks!

Cheers,
Griefed

**Comment by TheButterbrotMan** [comment]
In future i will not include mods that are allready present in the fallback list. 

Regards
Elias

**Comment by Griefed** [comment]
No worries, it's not a big deal. 🙂

Stay safe and stay awesome.

Cheers,
Griefed

**Comment by Griefed** [comment]
It's the little things. 😊 Thanks for being so thorough with these requests and taking the time to make sure we get no false-positives into the list.

This was on Music Duration Reducer:
![image](https://user-images.githubusercontent.com/44273438/161617892-181755bb-ce1f-4da6-9d5c-c4b1d31a4e4f.png)

**Comment by Griefed** [comment]
The specified mods are available in the fallback-list as of version [3.1.0](https://github.com/Griefed/ServerPackCreator/releases/tag/3.1.0).

For future changes to the fallback-list, in addition to every release shipping the new list, you can now manually check for updates via the `Menu -> File -> Update Fallback Clientside Modslist`.
This also means that manually changing the property `de.griefed.serverpackcreator.configuration.fallbackmodslist` is now discouraged.

Cheers,
Griefed
