### ISSUE TITLE
[Improvement request]: More more compatibilites

### ISSUE THREAD

**Issue by TheButterbrotMan** [Griefed/ServerPackCreator#319]
### Whats the feature you would like to be added?

https://www.curseforge.com/minecraft/mc-mods/movement-vision
https://www.curseforge.com/minecraft/mc-mods/fps-monitor
https://www.curseforge.com/minecraft/mc-mods/effective
https://www.curseforge.com/minecraft/mc-mods/ngrok-lan
https://www.curseforge.com/minecraft/mc-mods/absolutely-not-a-zoom-mod
https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
MOAR!

**Comment by Griefed** [comment]
The specified mods are available in the fallback-list as of version [3.1.0](https://github.com/Griefed/ServerPackCreator/releases/tag/3.1.0).

For future changes to the fallback-list, in addition to every release shipping the new list, you can now manually check for updates via the `Menu -> File -> Update Fallback Clientside Modslist`.
This also means that manually changing the property `de.griefed.serverpackcreator.configuration.fallbackmodslist` is now discouraged.

Cheers,
Griefed
