### ISSUE TITLE
refactor: Rename logs directory to somewhat that doesn't contain name of the directories which Minecraft uses

### ISSUE THREAD

**Issue by whitebear60** [Griefed/ServerPackCreator#32]
Minecraft puts its logs into `logs` directory, so if I started MC many times, it becomes hard to find SPC logs there. I propose to rename SPC logs directory to something like SPC_logs or move the SPC logs directory to server_files directory.

**Comment by Griefed** [comment]
You are not supposed to put the ServerPackCreator-X.X.X.jar file in the same directory as your modpack. Remember the wikis we made? 
They state that you're supposed to put the .jar in the parent directory, resulting in a structure like this:
```bash
.
├── serverpackcreator.conf
├── logs
├── server_files
├── ServerPackCreator-X.X.X.jar
└── Modpack_directory
    ├── config
    ├── saves
    ├── defaultconfigs
    └── mods
```

**Comment by whitebear60** [comment]
Oops... My fault :)
