### ISSUE TITLE
[Improvement request]: More clientside mods

### ISSUE THREAD

**Issue by TheButterbrotMan** [Griefed/ServerPackCreator#322]
### Whats the feature you would like to be improved?

https://www.curseforge.com/minecraft/mc-mods/mod-credits
https://www.curseforge.com/minecraft/mc-mods/durability-notifier
https://www.curseforge.com/minecraft/mc-mods/modmenu
https://www.curseforge.com/minecraft/mc-mods/defaultsettings-fabric
https://www.curseforge.com/minecraft/mc-mods/dynamic-fps
https://www.curseforge.com/minecraft/mc-mods/blur-fabric
https://www.curseforge.com/minecraft/mc-mods/rebrand
https://www.curseforge.com/minecraft/mc-mods/better-biome-blend
https://www.curseforge.com/minecraft/mc-mods/eggtab-fabric

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Available as of [3.2.0](https://github.com/Griefed/ServerPackCreator/releases/tag/3.2.0)

Thanks for the report!

Cheers,
Griefed
