### ISSUE TITLE
[Bug]: Client side mods are included despite fallback list

### ISSUE THREAD

**Issue by TheButterbrotMan** [Griefed/ServerPackCreator#323]
### What happened?

I generated a serverpack and there still mods from the fallback list eg. blur

### What did you expect to happen?

Blur goes poof

### Version

3.1.0

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/gdBHo8IWiZ

**Comment by TheButterbrotMan** [comment]
fallback name "Blur-" mod name "blur-2.4.1.jar"

**Comment by Griefed** [comment]
Availoable as of [3.2.0](https://github.com/Griefed/ServerPackCreator/releases/tag/3.2.0)

Thanks for the report!

Cheers,
Griefed
