### ISSUE TITLE
[Feature request]: Allow a save to be distributed as a world

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#325]
### Whats the feature you would like to be added?

Allow a saved world to be distributed as a world thus force enabling of the worlds/ folder.

### Anything else you would like to add?

Mmmmm donutsssssss! droooooool

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Kreezxil,

thanks for opening this feature request.

By `allow a save to be distributed as a world` do you mean including a world, from any modpack, to be included in the server pack?
As of yet I am not quite sure what you mean by this feature request.

Cheers,
Griefed

**Comment by kreezxil** [comment]
scenario:
the pack dev has created several worlds for testing, but one them they want
to be distributed with the pack. to include the server pack, so they would
be given the option to specify one of saved worlds, or even a world stored
somewhere else.

**Comment by Griefed** [comment]
ServerPackCreator allows you to specify words and external folders.
The latter even a *source* -> *destination* combination for files and folders.

Examples can be found here: https://wiki.griefed.de/en/Documentation/ServerPackCreator/ServerPackCreator-Help

Does any of these help you out, or do ypu require something else?

Cheers,
Griefed

**Comment by kreezxil** [comment]
you've thought of everything, at least in this regard, that helps me out,
you can close this.
