### ISSUE TITLE
[Feature request](5.x): Button to reset clientside-mods field to default value or config value

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#328]
### Whats the feature you would like to be added?

Have a microscope icon appear if the setting to detect client side mods is enabled. Clicking it will add mods to the window. The user will naturally have to clean that list afterwards, as it's just a tool.

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Kreezxil,

thanks for opening this feature request!

A reset button, so to speak? Yeah, I can see that, that makes sense.

**Comment by kreezxil** [comment]
let's go with that. see where it goes.

**Comment by Griefed** [comment]
I'll add this to the 5.x milestone where a rework of the GUI is going to happen anyway. Much easier to plan a new GUI with space for multiple new buttons, tjan to forcefully squiah one into the current mess of a GUI

Cheers,
Griefed

**Comment by Griefed** [comment]
Implemented as of 3.14.0-beta.7
There's buttons to revert the clientside-only mods and copy-directories fields to the value of the last loaded/saved configuration, as well as a button to reset to the factory-default setting.

Feel free to reopen this issue if something regarding this topic comes up again.

3.14.0 will leave beta Soon™.

Cheers,
Griefed
