### ISSUE TITLE
[Feature request](5.x): Reset the clientside-mods upon change of the modpack-directory

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#329]
### Whats the feature you would like to be added?

![image](https://user-images.githubusercontent.com/3880072/167689539-e11ed3d7-a652-4e38-b928-ca3e7c77cbe7.png)

When choosing a new pack 1, the mod list 2 should auto refresh if the setting to autodetect is enabled.

currently using 3.4.1

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Kreezxil,

thanks for this issue.

I consider it more a bug, than a feature request. I'll change SPCs behaviour accordingly before the next release. Good catch.

Cheers,
Griefed

**Comment by Griefed** [comment]
Please see whether the adjusted behaviour for the *Directories to Copy*-field is now more user-friendly with 3.5.0-alpha.3: https://github.com/Griefed/ServerPackCreator/releases/tag/3.5.0-alpha.3

**Comment by Griefed** [comment]
Nah, words are not failing you. As I mentioned in the comment above, I misinterpreted this issue back when you created it. 

As I said, I thought you were talking about re-validating the `Directories to copy`-field.
A reset button for the clientside-mods will be added together with the indicator you asked for in https://github.com/Griefed/ServerPackCreator/issues/328.
However, those will be added in another milestone, where a rework of the GUI is going to happen anyway.

**Comment by kreezxil** [comment]
alright that's cool then.

**Comment by Griefed** [comment]
Implemented as of 3.14.0-beta.7
There's buttons to revert the clientside-only mods and copy-directories fields to the value of the last loaded/saved configuration, as well as a button to reset to the factory-default setting.

Feel free to reopen this issue if something regarding this topic comes up again.

3.14.0 will leave beta Soon™.

Cheers,
Griefed
