### ISSUE TITLE
[Bug]: wildcard not working in 3.4.1

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#333]
### What happened?

config: https://haste.zneix.eu/yremugokah
spc log: https://haste.zneix.eu/ecynorybyh

i told it some mods to exclude, it copied them anyway, at least it copied toast-control

### What did you expect to happen?

not to copy mods when using wildcard or (substring)

### Version

3.4.1

### Relevant log output

```shell
config: https://haste.zneix.eu/yremugokah
spc log: https://haste.zneix.eu/ecynorybyh
```

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kreezxil** [comment]
NEVER MIND. Toast Control changed it's file name on update. Problem fixed.

**Comment by Griefed** [comment]
> NEVER MIND. Toast Control changed it's file name on update. Problem fixed.

I hate it when mods do that. Glad that you got it resolved, though.

Cheers,
Griefed
