### ISSUE TITLE
[Improvement](5.x): Move the Java setting from the serverpackcreator.conf to ServerPackCreator wide config

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#334]
### What happened?

For the line that says optional java. It would be super sweet if that value was populated into the java field for the local test server. I know it doesn't need to go into the archive tho.

### What did you expect to happen?

For optional java line to be used in the test servers script.

### Version

3.4.1

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Kreezxil,

thanks for opening thisnissue. I'd consider this more of a feature request, than a bug report.

In the sense that there could be a checkbox which would allow a user to use the Java setting for the Java variable in the start scripts.

However, that being said, the unzipped server *can* be viewed as a testserver, I guess, but was originally intended to be the one you upload to your server, for example via FTP to Bisect or something like that, for immediate use.

On the one hand it could make local tests a bit easier, but on ther other there are a couple of potential issues with something like this.

The DAU could distribute the unzipped one, with the custom Java path, and then come back to me complaining that it doesn't work for their users.
It would also mean branching out in the creation of the start scripts, leading to more maintanence on my part.

I'll have to think about this one and how it could best be implemented, with as little risk as possible.

Cheers,
Griefed

**Comment by kreezxil** [comment]
in which case the optional java line isn't even needed because it's not
used anywhere.

**Comment by Griefed** [comment]
It's used for the modloader server installation

**Comment by Griefed** [comment]
Hence the `(optional)` in the label of the field.

**Comment by kreezxil** [comment]
it doesn't even matter for that, java 8 will install the modloaders and
their libraries just fine. that line is sus now. :( "sadge" It's the
running of the server itself where the java version matters most. Which is
what I supposed all this time that line was meant to be.

**Comment by Griefed** [comment]
Allowing a user to configure with which Java to install the modloader server, should a user so desire, *does* matter, in case Forge or Fabric, and in future Quilt, decide to change something about their server installations.
We already know that newer Forge versions require a different Java version for running the server, so it is not far fetched to assume that the installation might, too. Hence the need to allow a user to specify with which Java to install the modlaoder server during server pack creation.

The Java installation with which the server runs is `java` by default, and can be changed in the start scripts.
A server pack is intended to be distributed via services like CurseForge or similar services, so you never know which Java version a given user has available or where it is installed, but we *can* assume that they have a default available, in the case of Linux, under the alias `java`.

Running multiple Minecraft servers on one machine is considered an edge case, as most users simply want a server pack they can download and run as is and play with their friends. For more specialized use-cases, the variable can be edited in the scripts.

**Comment by kreezxil** [comment]
there needs to be a tooltip that says "this is not the java used in the
start script but the java used to actually install the mod loader and its
libraries". Or have it hidden in the properties file, out of site, out of
mind, until it's needed, and then the wiki explains that.

**Comment by Griefed** [comment]
I agree on an improved tooltip and wiki entry.

Furthermore, the Java-path-field was also added in case a given user does not, somehow, have `java` in their path variable, so SPC could not automatically determine a path to a valid Java installation from the given systems environment. This resulted in crashes during the server installation during server pack creation way back in version 1.x, where the path could not be edited.

**Comment by Griefed** [comment]
> maybe rename it to "fallback java" or remove it and have it in the properties file.

That's a great idea. Move it to the properties and therefor, in a later version, to a settings menu. Makes a lot more sense.

**Comment by Griefed** [comment]
Will also be taken care of in 3.14.x.
It turned out to be an API change, therefor, I am making the needed changes now.

The Java path setting will be removed from server pack-related configurations completely.
The setting can then be found in the serverpackcreator.properties.

Everything else remains the same. SPC will try to autodetect the Java executable/binary.
If the modloader server checkbox is ticked, and if no valid Java is specified, a prompt will open where you will be able to set it accordingly. 

Symlinks/lnks should still work. (I still hate them, though. At least when handling them in Java)

**Comment by Griefed** [comment]
I haven't heard back from you regarding this, so I assume this has been satisfactory to you. I'm closing this issue. Feel free to reopen it if something about this topic comes up again. 🙂

3.14 will leave beta Soon™.

Cheers,
Griefed

**Comment by kreezxil** [comment]
I appreciate forward thinking, but if we are to forward think "exagerated",
imagine your program gains sentience in the future one day and it wants to
work for a donut shop, should we bundle donut glaze with it just for that
future scenario?
