### ISSUE TITLE
[Bug]: server.properties comes in blank

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#335]
### What happened?

Gave it a locaiton of a server.properties to load, but the file came in blank. the file is not blank.

### What did you expect to happen?

for it to not blank out the file.

![image](https://user-images.githubusercontent.com/3880072/169724886-dfbc6194-c6bc-414f-81b6-a12e65220a98.png)

actual file: hastebin.com/akisalozem

### Version

3.5.0-alpha.3

### Relevant log output

```shell
configuration: https://haste.zneix.eu/piqyziducu

log: https://hastebin.com/oretagumab
```

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Lolwut, okay, that's a strange one.

I'll investigate asap and report back to you.

Thanks for the report!

**Comment by Griefed** [comment]
Can not be reproduced by either Kreezxil or me.
May have been due to Windows Read-Only settings, but unsure.
