### ISSUE TITLE
[Bug]: Can't create pack in alpha.8

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#336]
### What happened?

I press the generate and it gets to the end says it made the zip but there is no popup. The log says it couldn't download forgeinstaller.jar

### What did you expect to happen?

to make the popup and let me browse to the server to test it locally

### Version

3.5.0-alpha.8

### Relevant log output

```shell
https://gist.github.com/kreezxil/5fd6e690f5bfc27628880bec80686514
```

### Anything else you would like to add?

Did this in Windows 10.

Tried both the exe and the jar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kreezxil** [comment]
note that 3.4.1 is able to download the forge installer and create the pack.

**Comment by Griefed** [comment]
Huh, interesting. Thabks for the report, I'll investigate and try to reproduce this.

Strange that it already failed at this part, though:
> ERROR [pool-3-thread-1] (ServerPackHandler.java:1407) - Failed to create directory C:/Users/roger/Desktop/serverpackcreator/server-packs/World of Dragons II-4.17.66

**Comment by Griefed** [comment]
I can not for the life of me reproduce this issue on my end.
I'm currently implementing some checks for read-permissions, maybe we can identify this issue that way. 

This somewhat reminds me of your issue with the server.properties-file a while back....

**Comment by kreezxil** [comment]
yeah it does. I even ran Tweaking.com's tool to fix and scan my windows
system before I posted this report.

**Comment by Griefed** [comment]
Can you try with 3.5.0-beta.1 and report back? https://github.com/Griefed/ServerPackCreator/releases/tag/3.5.0-beta.1

**Comment by kreezxil** [comment]
3.5.0-beta.2 created the pack perfectly, thank you. ;)

**Comment by Griefed** [comment]
Glad to hear! I'll go ahead and close this issue.

Cheers,
Griefed
