### ISSUE TITLE
[Bug]: modal windows not centered

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#337]
### What happened?

![image](https://user-images.githubusercontent.com/3880072/172057994-0449c8e6-92f3-4c3f-94a6-cb1a10067c57.png)

In 350 beta.2 all the modal windows are opening in the bottom right corner and just a bit under the task bar too.

the log: https://haste.zneix.eu/tuqowuwasi

### What did you expect to happen?

modal windows to open centered on the screen or app.

### Version

3.5.0-beta.2

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kreezxil** [comment]
correcton: all the modal windows that open when you click the green folders. The ones you get from the file menu are opening centered on the app/screen.

**Comment by Griefed** [comment]
Good catch, thanks!

**Comment by Griefed** [comment]
Fixed in the next beta, which is on its way. :)

**Comment by Griefed** [comment]
Fixed as of [3.5.0](https://github.com/Griefed/ServerPackCreator/releases/tag/3.5.0).

If you encounter anything else, do not hesitate to open a new issue. 🙂

Cheers,
Griefed
