### ISSUE TITLE
[Improvement request]: 3.5.0-beta.3 icon grouping in task bar

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#342]
### Whats the feature you would like to be improved?

Not sure if its a thing with my OS or not, but SPC is being grouped with the first java app that I have opened, in this case ATL.

![image](https://user-images.githubusercontent.com/3880072/173449390-950ef6f6-c2f9-4a48-a02b-ef15b2c2090f.png)

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Kreexzil,

thanks for this request.

In theory this might by something I can do something about, I'll have to do some research first.

I'll get back to you about this.

Cheers,
Griefed

**Comment by Griefed** [comment]
Tried to reproduce it, but no luck so far. ServerPackCreator and ATLauncher get separate icons and do not get grouped together under Windows.

Tried to find something in Java which would allow me to have control over how ServerPackCreator is grouped in a given taskbar,but so far no luck.

What OS are you using there? Linux, I assume?
I know that on Windows one can configure how applications are grouped together. Not sure for other OS'.

**Comment by kreezxil** [comment]
Did I fail to say it was Linux?

**Comment by kreezxil** [comment]
Yep, I failed to say it. The specific stats. My reports will be concentrating on Linux btw, now that ATL can fully export mod packs as both cf and Modrinth without issue, neither will reject said mod pack. Meaning I no longer need to go to windows except for a game that refuses to run under wine or Proton, which is quite rare these days. GDL is rapidly get back to where it was before the API screwery by cf began. Can't wait for that because I hate ATL's choice of fonts and how a few other things.

```
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.94.0
Qt Version: 5.15.4
Kernel Version: 5.15.48-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × AMD FX(tm)-8350 Eight-Core Processor
Memory: 23.4 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 750 Ti/PCIe/SSE2
```

**Comment by kreezxil** [comment]
Alright this was OS dependent, Linux supports grouping by program type on the Taskbar, it sees both ATL and SPC as java programs and not the very specific apps that they are. Undoing the setting splits them out.

![image](https://user-images.githubusercontent.com/3880072/176205370-28068395-fd1f-48cf-875d-8fcf4d9efa0a.png)

**Comment by Griefed** [comment]
Good to know, thanks!
