### ISSUE TITLE
[Bug]: Missing Window

### ISSUE THREAD

**Issue by TheButterbrotMan** [Griefed/ServerPackCreator#346]
### What happened?

After the server pack has been generated, the "do you want to open the directory" window no longer opens.

### What did you expect to happen?

Giving me a easy time by opening the window

### Version

3.5.1

### Anything else you would like to add?

Du hast es wieder kaputt gemacht! :(

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheButterbrotMan** [comment]
Even better: Nothing opens, but I can't press anything in the ServerPackCreator anymore either

**Comment by TheButterbrotMan** [comment]
Even better 2: It just stucks. Cant close it either.

**Comment by Griefed** [comment]
Moin TheButterbrotMan,

lass mir bitte Logs zukommen damit ich das untersuchen kann.

**Comment by Griefed** [comment]
Ich kann dieses Verhalten von meiner Seite nicht bestätigen. Auch nach der Generation mehrerer Server Packs bleibt SPC funktional.

Kannst du mir, zusätzlich zu den Logs, noch beschreiben was genau du getan hast bevor SPC sich bei dir so verhalten hat?

**Comment by TheButterbrotMan** [comment]
Bin auch nicht mehr in der Lage das zu reproduzieren. Anscheinend eine einmailge Sache. Falls es nochmal auftritt melde ich mich.

**Comment by Griefed** [comment]
Klingt mir eher danach dass dein System zu dem Zeitpunkt ausgelastet war. Hast du parallel einen Minecraft Server, Minecraft und/oder weitere Anspruchsvollen Anwendungen laufen gehabt? Das würde das beschriebene Verhalten verursachen bzw. das Verhalten von SPC beeinflussen können. Das wär dann auch kein Problem seitens SPC. Wenn System ausgereizt, dann alles lahm 😂

Aber jo, sag bitte bescheid wenn du das nochmal haben solltest du das Problem reproduzieren kannst. 🙂 Dann schau ich mir das nochmal an.

**Comment by TheButterbrotMan** [comment]
> 

Nope, nur Serverpackcreator war am Laufen. Und YouTube, das hat auch ohne Probleme funktioniert.
