### ISSUE TITLE
[Feature request](5.x): Custom comment in start scripts

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#347]
### Whats the feature you would like to be added?

When the version field is filled out. Have SPC automatically inject that into a comment in the start scripts, or in a file called VERSION.TXT.

With this it will make it easier to get information from the player so that one can know which old pack they need to regenerate in SPC.

for reference:

```
ShadowTrolll — Yesterday at 6:24 AM
Ok whoever made the start.bat script for WoD 1 server should quickly retract it. In it's current state it works in system32 windows folder and creates all minecraft server files there. Which is, obviously, very dangerous, bad and not functioning as intended. I think I should tag @Kreezxil as this is a pretty serious issue

ShadowTrolll — Yesterday at 7:03 AM
Here is a fix (of questionable quality) that works on my PC. Windows 10 Home 64-bit OpenJDK Temurin 1.8.0_332-b09
:: Start script generated by ServerPackCreator.
:: This script checks for the Minecraft and Forge JAR-files, and if they are not found, they are downloaded and installed.
:: If everything is in order, the server is started.
@ECHO off
SetLocal EnableDelayedExpansion
Expand
start.bat
3 KB
[7:05 AM]
(Added line: 15, edited lines: 20, 43, 69) (edited)
June 26, 2022

@ShadowTrolll
Ok whoever made the start.bat script for WoD 1 server should quickly retract it. In it's current state it works in system32 windows folder and creates all minecraft server files there. Which is, obviously, very dangerous, bad and not functioning as intended. I think I should tag @Kreezxil as this is a pretty serious issue

Kreezxil — Today at 8:17 AM
@Griefed check this out.
[8:18 AM]
He's the author of Server Pack Creator

Griefed — Today at 8:31 AM
system32 windows folder and creates all minecraft server files there. 
Wat

[8:32 AM]
Nothing was added, changed, updated or deleted
[8:32 AM]
I just run such a start.bat file myself, generated with the latest version of SPC.
[8:37 AM]
I don't see the mentioned change in line 69. Looks like the default to me
[8:41 AM]
The working directory is at no point system32
[8:41 AM]

[8:41 AM]

[8:41 AM]

[8:41 AM]


ShadowTrolll — Today at 9:45 AM
When I ran it as standard user the target folder was correct but the script errored out. When I ran it as admin (which I do all scripts to-be-sure) the directory was system32 and the script did not error out (edited)

@Griefed
I don't see the mentioned change in line 69. Looks like the default to me

ShadowTrolll — Today at 9:46 AM
Removed one - from version as windows (I think generally) uses that to get java version
[9:47 AM]
Might be version specific but don't think so
[9:49 AM]
I have no reason to lie but if you need proof, I can run the original script again

Griefed — Today at 9:50 AM
Do. Not. Run. Scripts. As. Admin. That#s just asking for trouble.

ShadowTrolll — Today at 9:50 AM
Well allright

Griefed — Today at 9:51 AM
By executing as admin you automatically change to system32. That's aWindows thing

ShadowTrolll — Today at 9:51 AM
Yeah but you can include line 15 to make sure it is the correct directory "no matter what"

Griefed — Today at 9:54 AM
Aye, a little safety net

ShadowTrolll — Today at 9:57 AM
Also for some reason I had to remove the Optional
[9:57 AM]
Otherwise it refused to run when working directory was correct
[9:58 AM]
Idk why maybe something with my windows install but worth checking out in case more ppl have this issue

Griefed — Today at 10:09 AM
Hmmm, strange, that

@ShadowTrolll
Removed one - from version as windows (I think generally) uses that to get java version

Griefed — Today at 10:23 AM
Ah, yeah in that case the script was generated with an older version SPC. This has been fixed a couple of versions ago. 

@Griefed
Ah, yeah in that case the script was generated with an older version SPC. This has been fixed a couple of versions ago. 

Kreezxil — Today at 11:37 AM
@ShadowTrolll which of my packs, and which version was it that you used. Now that we've isolated what the problem is, I can regenerated the start/installer script.
NEW

@Kreezxil
@ShadowTrolll which of my packs, and which version was it that you used. Now that we've isolated what the problem is, I can regenerated the start/installer script.

ShadowTrolll — Today at 11:38 AM
```

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Kreezxil,

thanks for this feature request.
When you say "version field", are you talking about the server pack suffix?

**Comment by kreezxil** [comment]
yes, i am. because when i asked the other day what version of my pack the
guy was using, i wasn't referring to java. :)

**Comment by Griefed** [comment]
I will probably introduce a separate field, then, at some point.
Said field will be a custom comment which will be added to the beginning of the start scripts, after the usual 
```
# Start script generated by ServerPackCreator.
# This script checks for the Minecraft and Fabric JAR-Files, and if they are not found, they are downloaded and installed.
# Should this server pack come with the improved Fabric Server Launcher, then it is used instead of the old one.
```
stuff, so it would look something like this

```
# Start script generated by ServerPackCreator.
# This script checks for the Minecraft and Fabric JAR-Files, and if they are not found, they are downloaded and installed.
# Should this server pack come with the improved Fabric Server Launcher, then it is used instead of the old one.
#
# Timey whimey, wibbly wobbly, this is a custom comment, oh jolly!
```
where `Timey whimey, wibbly wobbly, this is a custom comment, oh jolly!` will be customizable.

Reasoning:
A suffix *can* be a version, but a version is not always a suffix. Mixing those two and deaclaring two different uses for one such text would be very limiting to the user.
It would be better to have two separate values to configure. One for the suffix of the server pack and one for the comment in the start script.

Thoughts?

**Comment by Griefed** [comment]
This will be available in 3.14.x via custom script templates and script settings.

A preview of the script settings is available in the alpha release for 3.14.x, which you can get here: https://github.com/Griefed/ServerPackCreator/releases/tag/3.14.0-alpha.2

Steps for creating the requested functionality:
1. Copy the default templates to a name of your choosing (keep the file endings, they determine the start script file endings)
2. Customize the copied tempaltes and add the desired placeholder, for example `MY_VARIABLE="SPC_MY_VARIABLE_SPC"` in shell scripts, `MyVariable = "SPC_MY_VARIABLE_SPC"`
3. In the ServerPackCreator GUI script settings table, add a placeholder `SPC_MY_VARIABLE_SPC` and a value for said placeholder, `Awesome server pack created by Kreezxil!`

This would result in the following variable settings in the created start scripts:
1. Shell scripts: `MY_VARIABLE="Awesome server pack created by Kreezxil!"`
2. PowerShell scripts: `MyVariable = "Awesome server pack created by Kreezxil!"`

ServerPackCreator replaces any occurance of `SPC_MY_VARIABLE_SPC`, or any other placeholder for that matter, with the corresponding, user-defined, value.
Use caution with your placeholder names 😀I suggest always using a pre- and suffix, like in the example above `SPC_` and `_SPC` respectively.

A detailed walkthrough will be available in the wiki, too. Once 3.14 goes live.

**Comment by Griefed** [comment]
You can of course use this system to place some custom text in your scripts, too. You are not bound to using it on variables. The above was just an example. You can add comments, too.

**Comment by Griefed** [comment]
I haven't heard back from you regarding this, so I assume this has been satisfactory to you. I'm closing this issue. Feel free to reopen it if something about this topic comes up again. 🙂

3.14 will leave beta Soon™.

Cheers,
Griefed
