### ISSUE TITLE
[Feature request]: Detect and warn about 32 bit java

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#392]
### Whats the feature you would like to be added?

Have the scripts detect and warn with a prompt similar to "I agree" when 32-bit java is being used.

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Kreezxil,

thanks for this feature request.
Would you happen to know how this could be done in shell scripts?

If not, could you provide a working solution for the bash scripts, please?
I'll take a look at Powershell after I'm done fixing #332.

Cheers,
Griefed

**Comment by kreezxil** [comment]
[image: image.png]

[image: image.png]

**Comment by Griefed** [comment]
> [image: image.png]
>
> [image: image.png]

I'm afraid the images aren't loading.

**Comment by kreezxil** [comment]
![image](https://user-images.githubusercontent.com/3880072/180237767-c77d511c-faf6-4c95-8159-e7061075b4a8.png)

**Comment by Griefed** [comment]
I'm afraid I can not reproduce this behaviour on my part. We will need to find a better, more reliable solution for this.
![image](https://user-images.githubusercontent.com/44273438/180624969-c16fd2c6-4b3d-4d95-affb-7de22f8cb337.png)

**Comment by kreezxil** [comment]
What you are experience is called user error. That user is you. Look at the case for the word **Bit** and how you typed it into the bash shell.

![image](https://user-images.githubusercontent.com/3880072/180650847-dd991af8-3915-4a6a-9e27-12160fa6d802.png)

What the command does is change the default reporting channel of java from stderr to stdout so that we can pipe it to grep, which if it fails does the command after the || (I call it **OR**). So, yes in both of your tests it would print the string after the echo because it couldn't find "64-**b**it" when you should've told it to scan for "64-**B**it".

And you subsequent tests without an or-clause also ring true to produce nothing, because of looking for "64-bit" when the output is clearly "64-Bit".

There is an option in grep that allows you to ignore the case, you can change the grep to read
```bash
java -version 2>&1 | grep -i "64-Bit" || echo "false"
```
btw you don't have to echo false, you could set a variable, write a file, launch a program or script for the or-clause.

**Comment by Griefed** [comment]
> What you are experience is called user error. That user is you. Look at the case for the word Bit and how you typed it into the bash shell.

Could have phrased that a little less condescendingly, or added an emoji to indicate it being a joke. I will assume you meant it as a joke. Just something to keep in mind for the next time. 🙂

`java -version 2>&1 | grep "32-Bit" || echo "64bit"`

Something like this would yield the desired result. If a 64-bit Java is installed, this will not return the text from the echo, but the line of -version which specifies the full version installed on the system, meeeh... Otherwise, it will echo the specified text.

I know about the `||`-operator. Classic OR-operator.

**Comment by kreezxil** [comment]
I wasn't phrasing it condescendingly, it was matter-of-fact. Was only meant
be taken thus. But sure thanks for letting me know that I can by quite a
bit too literal in my explanations.

**Comment by Griefed** [comment]
So can I, no heart feelings. Just a friendly FYI. Hey, I mean, I need to get used to using the tone-indicators you mention on the BPS Discord server, too. 😂

**Comment by Griefed** [comment]
See [3.13.0](https://github.com/Griefed/ServerPackCreator/releases/tag/3.13.0) for a simple implementation of this. Should `java -version` contain `32-Bit` a warning will be printed, but the startup of the server will be continued. The console will contain the information so the attentive admin should catch it.

Considering 32-Bit Java is, thankfully, dying out, it should be enough all things considered.

Cheers,
Griefed
