### ISSUE TITLE
[Feature Request](4.x) Set working directory to sub-directory in users home directory

### ISSUE THREAD

**Issue by nekomaster1000** [Griefed/ServerPackCreator#438]
### Whats the feature you would like to be added?

Currently, ServerPackCreator is downloadable as an EXE file. 
Launching this EXE, without warning, creates subdirectories for the program in the folder you opened the EXE in. 

I am requesting that future versions of the program are packaged in a ZIP file that contains the EXE alongside it's subdirectories, so that future newbies to the program know that those directories are going to be created/used ahead of time.

### Anything else you would like to add?

That's all. Thanks for the help on the Bisect Discord, dude!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Hey Nekomaster,

I won't be changing the packaging to a .zip.
.exe and .jar will stay, but may get additions for other OS specific executable later on.

What I might end up doing, however, is to let the  inattentive user know that files and folders will be created when they first run it. 

I'll be blunt here. I personally dislike the idea greatly. If someone runs a complete program from, say, the downloads directoy, or even their desktop, and said program does its thing....yeah tough shit. What do people expect? Put it in a folder, **then** test things...used to be common sense, people used theor brains, but that seems to fly out of the window more and more these days. I'd hate to see how such people run productive IT environments. 

That said, I'll still think up a nice looking way for a later version.

I may personally dislike, or even hate it, but objectively speaking, it is a valid request.

Cheers,
Griefed

**Comment by Griefed** [comment]
Hey Nekomaster,

I won't be changing the packaging to a .zip.
.exe and .jar will stay, but may get additions for other OS specific executable later on.

What I might end up doing, however, is to let the  inattentive user know that files and folders will be created when they first run it. 

I'll be blunt here. I personally dislike the idea greatly. If someone runs a complete program from, say, the downloads directoy, or even their desktop, and said program does its thing....yeah tough shit. What do people expect? Put it in a folder, **then** test things...used to be common sense, people used theor brains, but that seems to fly out of the window more and more these days. I'd hate to see how such people run productive IT environments. 

That said, I'll still think up a nice looking way for a later version.

I may personally dislike, or even hate it, but objectively speaking, it is a valid request.

Cheers,
Griefed

**Comment by Griefed** [comment]
First implementation available as of [4.0.0-alpha](https://github.com/Griefed/ServerPackCreator/releases/tag/4.0.0-alpha.12)

ServerPackCreator will use the `ServerPackCreator`-directory from the users home-directory now. :) I will leave this issue open until the full release of SPC 4 in case any further conversation, discussion or feedback is required regarding this issue.

Cheers,
Griefed

**Comment by Griefed** [comment]
Available as of [4.x](https://github.com/Griefed/ServerPackCreator/releases/tag/4.0.1)

Cheers!
