### ISSUE TITLE
[Bug]:  Only forge respects user_jvm_args.txt.

### ISSUE THREAD

**Issue by MissPotato** [Griefed/ServerPackCreator#451]
### What happened?

I was trying to figure out why my fabric server was getting OoM errors. We tried bumping it all the way up to 10 gigs and weren't seeing any improvement. After messing around with Spark for a while I noticed the server was only allocated a little bit over 3 gigs. After looking at the script user_jvm_args.txt is only inside the forge section. This can be circumvented by copy and pasting the args from the .txt to the args variable inside the script directly.

### What did you expect to happen?

Respect the user_jvm_args.txt in all loaders.

### Version

3.15.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Hey there,

thanks for the report!
Fabric using the jvm_args sounds new to me, maybe they changed that with newer versions.

What Minecraft and Fabric versions are you using on your server?

Cheers,
Griefed

**Comment by MissPotato** [comment]
I don't think I understand the question. Why wouldn't fabric support JVM boot args?

Regardless: Fabric 0.14.14 and minecraft 1.19.2

**Comment by Griefed** [comment]
I was referring to the txt file you mentioned. To my knowledge, only Forge uses said txt file, whilst Fabric uses regularly passed args via commandline.

I'll take a look with the versions you provided. :) 

Cheers,
Griefed

**Comment by MissPotato** [comment]
Oh, I think I see the issue here. I was assuming the script was reading the file and passing that to the launchers. Not a function of the actual launchers, sorry! I wasn't the one who installed the script, just someone who was trying to fix their server for them. Terribly sorry for the confusion.

**Comment by Griefed** [comment]
No worries! Could have well been a bug in ServerPackCreator, you never know.

SPC provides two scripts, one for linux, one for Windows.
Said scripts contain all necesssary information to run a Minecraft server. In the case of Forge, however, some of that information is exported to a separate file, which is then read by the Forge modloader during server launch. That file being the user_jvm_args textfile.
The Forge system seems to prefer it that way over passing all parameters via commandline old-school-style. No idea why, but oh well. It is what it is. :D

Cheers,
Griefed
