### ISSUE TITLE
[Bug]: Pre-Release 5.0.0-alpha.3 cannot input in some text fields

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Griefed/ServerPackCreator#455]
### What happened?

On my Linux Mint system, with Pre-Release 5.0.0-alpha.3 in addition to the file explorer not working (as reported already) I am also unable to enter the correct paths manually in the GUI. The only way I can edit is directly in the conf files.

### What did you expect to happen?

Should be able to manually enter paths in text fields.

### Version

Pre-Release 5.0.0-alpha.3

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya ClaudiusMinimus,

manually editing the paths for the modpack, server icon or server properties has been removed due to the filebrowser and other components setting the paths for you.

You mentioned the filebrowser not working: Does it not open at all, like Kreezxil reporten on the BisectHosting discord, or is something else the issue?

Cheers,
Griefed

**Comment by ClaudiusMinimus** [comment]
I can open the file explorer and drill-down, but I cannot select anything for the field. I would like to manually enter the paths and use the file browser. Linux auto-completes paths so nicely, that I often don't use drill-down menus.
![image](https://user-images.githubusercontent.com/17887664/228733350-a08bffa6-3f2d-43e5-aeb1-08f83dfaa87f.png)

**Comment by Griefed** [comment]
Ahhh I see. Alpha gotta alpha. The filebrowser is still incomplete.
Right-click on an entry in the tree on the left, or on an entry in the table on the right.
A context-menu will open will presents several options, allowing you to set the modpack-directory, server-icon or server.properties, depending on the file-type.

Buttons to do the same thing will come later.

**Comment by Griefed** [comment]
I'll go ahead and close this issue, as it is technically not a *bug*, but rather a not yet fully implemented and fleshed out feature.

The buttons will come Soon™, though. :)

Cheers,
Griefed
