### ISSUE TITLE
[Bug]: The app can't be opened on macOS because it's damaged

### ISSUE THREAD

**Issue by Atten007** [Griefed/ServerPackCreator#456]
### What happened?

Hello,

I have my own Pokemon mod pack for version 1.19.2. It's currently only available for clients and I want to make it available also for servers. Unfortunately, when I open the app on my Apple M1 MacBook Air, it says that the file is damaged, but I know, that the file **isn't** damaged. Is this a bug and if yes, can you please fix it?

Greetings,
Atten 😊

### What did you expect to happen?

I wanted to see that I can open the app without any errors.

### Version

5.0.0-alpha3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Atten007,

have you tried using a non-pre-release version yet? Alphas and betas are expected to have bugs or to not work at all in certain areas.

Could you please try [4.0.4](https://github.com/Griefed/ServerPackCreator/releases/tag/4.0.4) and report back to me whether that version works for you? 😊

Cheers,
Griefed

**Comment by Atten007** [comment]
4.0.4 is also damaged on my MacBook ☹️.

**Comment by Griefed** [comment]
Humm, very strange. A fix for this may take some time as the only MacOS at hand is a virtual machine, and MacOS VMs are not know for performing really well.

In the meantime, you may use the JAR-file in conjuction with Java 17.

**Comment by Griefed** [comment]
What version of macOS are you currently running?

**Comment by Atten007** [comment]
I'm using macOS 13.3

**Comment by Griefed** [comment]
Can't test this right now, but this may be a solution to this "problem": https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

Adding a security exception for ServerPackCreator might allow you to run it anyway. If this works, then it may be a workaround-becomes-expectation thing, as I have no other way of letting people use the DMG on macOS.

**Comment by Griefed** [comment]
Ok yeah, the DMG files seem to be *actually* broken, not just *Apples security system prevents us from running SPC*-broken.
Thanks for letting me know. I'll try and remedy this in a future release and get back to you when I got news on this topic. 😊

Cheers,
Griefed

**Comment by Griefed** [comment]
Just ran a test where, instead of a DMG, a PKG file was produced. I was able to run the PKG-installer and successfully install and run ServerPackCreator that way.

The next alpha release will provide a PKG instead of a DMG.
Thanks for letting me know about the broken DMG files :)

**Comment by Griefed** [comment]
Heya,

me again. Could you try the PKG from https://github.com/Griefed/ServerPackCreator/releases/tag/5.0.0-alpha.4 please? You may need to run it using Apples guide available at https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

Cheers,
Griefed

**Comment by Atten007** [comment]
Yes, I tried it and it worked :)

**Comment by Griefed** [comment]
Schweet, working macOS distributions! 😂
Thanks for the feedback.

I'll close this issue, then.

Take care!
Cheers,
Griefed
