### ISSUE TITLE
[Feature ask](MS8): Add arguments to command line to support output destination and config file location

### ISSUE THREAD

**Issue by RSNFreud** [Griefed/ServerPackCreator#457]
### Whats the feature you would like to be added?

Add two arguments to the command line: 

-config - This will allow you to specify where the config file is located
- output - This will allow you to specify where you want the server pack to be saved to.

This will help to share config files between multiple members of a modpack team easily rather then them having to go through the process of saving the config into their user directory.

### Anything else you would like to add?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya RSNFreud,

> This will help to share config files between multiple members of a modpack team

how would being able to use a specific config and saving the server pack to a specific location make sharing configs in a team easier? And which configs are you talking about in this context?

The way I see it, it wouldn't. Input and output remain the same, the config isn't changed, thus any team member would have to make sure their server pack config does not contain references with absolute filepaths anyway.

The commandline args themselves are a nice idea and will most likely be added in a later milestone.

Cheers,
Griefed

**Comment by RSNFreud** [comment]
> how would being able to use a specific config and saving the server pack to a specific location make sharing configs in a team easier? And which configs are you talking about in this context?

Currently the process to use a custom config is running with the `-cgen` arg, loading the config from the github repo, saving it and then running the serverpack command with the cli. This is just an easier and quicker way of doing it

**Comment by Griefed** [comment]
So it doesn't make sharing configs easier, just using a given config, as suspected.

Aight, sounds good. Will probably come with milestone 8, so don't hold your breath. :)

**Comment by Griefed** [comment]
Heyooo,
long time no speaky.

`-config` and `--destination` have been added as arguments to the CLI-mode.
`--destination` only works when used in combination with `-config`
Use them like this: 
`java -jar ServerPackCreator.jar -config /path/to/your_config.conf --destination /path/to/serverpacks/my_serverpack` 

If you want to test them, see https://github.com/Griefed/ServerPackCreator/releases/tag/7.0.0-alpha.1

**Comment by Griefed** [comment]
Available as of [7.0.0](https://github.com/Griefed/ServerPackCreator/releases/tag/7.0.0)

Help available at [HELP-Modes](https://github.com/Griefed/ServerPackCreator/blob/main/HELP.md#modes)

Enjoy! :)
