### ISSUE TITLE
[Bug]: PS1 incorrectly uses "JAVAARGS" variable name where "JAVA_ARGS" is used for variables.txt

### ISSUE THREAD

**Issue by Frontear** [Griefed/ServerPackCreator#460]
### What happened?

Essentially, the PS1 has a typo that is trying to source the "JAVAARGS" variable from the variables.txt file. This is invalid since by default, the variables.txt file has a "JAVA_ARGS".

The suspecting file can be found here: https://github.com/Griefed/ServerPackCreator/blob/dc0143059d050805f76e2299c847ecfb8aad8d1c/serverpackcreator-api/src/jvmMain/resources/de/griefed/resources/server_files/default_template.ps1#L24

It should be noted that the shell file uses the correct variable, solidifying this as a simple typo. Nothing major but it does break PS1 for windows users.

Line in shell confirming the correct variable: https://github.com/Griefed/ServerPackCreator/blob/dc0143059d050805f76e2299c847ecfb8aad8d1c/serverpackcreator-api/src/jvmMain/resources/de/griefed/resources/server_files/default_template.sh#L70

### What did you expect to happen?

Well, I expected it to source the right variable

### Version

Release 4.1.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Frontear,

thanks for the report. I'll fix this asap! 😊

Cheers,
Griefed

**Comment by Griefed** [comment]
Also a huge thanks for the detailed report!

**Comment by Griefed** [comment]
Fixed in [4.1.3](https://github.com/Griefed/ServerPackCreator/releases/tag/4.1.3) 😊
