### ISSUE TITLE
[Bug]: `Get-Content -Path` sometimes fails due to a PowerShell bug

### ISSUE THREAD

**Issue by Frontear** [Griefed/ServerPackCreator#462]
### What happened?

In essence, running `Get-Content -raw -Path $ExternalVariablesPath` for the variables.txt file in the default start.ps1 file can sometimes, on certain systems, result in a devious little error message.

![image](https://github.com/Griefed/ServerPackCreator/assets/31909298/eac5ceac-2e44-465f-bc42-15fc2c0eb821)

This has been reported numerous times over at LunaPixelStudios and until now I wasn't really sure what was causing it and usually encouraged people to hardcode their variables.txt data into the script itself as a workaround, but now I've found more info. 

Apparently this is an [issue](https://github.com/PowerShell/PowerShell/issues/6954) with PowerShell dating back to 5.1, which is installed on an overwhelming amount of Windows 10 and 11 PCs.

What's the fix? Replace `-Path` with `-LiteralPath` will fix it. Of course an alternative solution is to encourage updating to PowerShell 7, but considering that the vast majority of users are inexperienced, they may not be sure of how to do that, and since this project exists in the interests of having the end-user do as little as possible to get things working (via the start.ps1 scripts), i figure its a neat little change that'll help resolve a lot of confusion.

### What did you expect to happen?

It to work, and believe me it does. I don't know exactly why, but on some systems the command will error out, return a null array, and the rest of the script will fail spontaneously because the array cannot be accessed.

### Version

Release 4.1.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Frontear,

thanks for opening this issue, diving so deep into it and already providing a solution!
LunaPixelStudios continues to amaze me. 😊

Has `-LiteralPath` been proven to work on both systems, those with older powershell versions and those with new versions?

Cheers,
Griefed

**Comment by Griefed** [comment]
Plese see whether [4.2.0](https://github.com/Griefed/ServerPackCreator/releases/tag/4.2.0) fixes this issue for you. :)

Cheers,
Griefed

**Comment by Griefed** [comment]
Heyo,

it's been two weeks. Have you had time to check whether aforementioned release fixed the issue for you?

Cheers,
Griefed

**Comment by Frontear** [comment]
Hi, yeah running a test it seems it works fine now. Thanks a lot for the speedy fix
