### ISSUE TITLE
[Feature ask]: NeoForge Support

### ISSUE THREAD

**Issue by AzureDoom** [Griefed/ServerPackCreator#465]
### Whats the feature you would like to be added?

NeoForge is a fork of Forge from all the old maintainers that left Minecraft Forge in the sole hands of Lex only. 

### Anything else you would like to add?

Here is the website for the project! https://neoforged.net/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya AzureDoom,

thanks for the request, I'll check it out Soonish™. It's probably going to be available in version 5 at the earliest, though.

Cheers,
Griefed

**Comment by Griefed** [comment]
Heyo AzureDoom,

5.0.0-alpha.21 features NeoForge support, if you would like to give it a go: https://github.com/Griefed/ServerPackCreator/releases/tag/5.0.0-alpha.21

I'll update you once 5.0.0 reaches beta-stage and then again once 5.0.0 goes live. :)

Cheers,
Griefed

**Comment by AzureDoom** [comment]
![image](https://github.com/Griefed/ServerPackCreator/assets/7415711/509b01cc-67ab-4de6-9530-70f32cc4ffa8)
getting this when selecting Prepare Local Server so it has the needed installer.

**Comment by Griefed** [comment]
Interersting.

In the meantime, just use the start scripts, as they work just fine afaik. The local server thing is, after all, just a convenience for speeding up local testing on your machine.

**Comment by Griefed** [comment]
A fix will be available with Pre-Release 5.0.0-alpha.24, which should be available Soon™.

Cheers,
Griefed

**Comment by Griefed** [comment]
Fix for the installer check available as of [5.0.0-alpha.24](https://github.com/Griefed/ServerPackCreator/releases/tag/5.0.0-alpha.24)

**Comment by Griefed** [comment]
Haven't heard any complaints about the new NeoForge support for quite a while now, so I assume it is working as expected for the time being (alpha is alpha after all).

I'll go ahead and close this issue, but feel free to reopen it or create a new issue if you discover any issue with the NeoForge support.

Cheers,
Griefed
