### ISSUE TITLE
[Improvement Ask]:  clientside modlist filter additions

### ISSUE THREAD

**Issue by Devilswarchild** [Griefed/ServerPackCreator#466]
### Whats the improvement you would like to be made?

[ESSENTIAL Mod](https://legacy.curseforge.com/minecraft/mc-mods/essential-mod) - clientside lan mod

[ModernFix](https://legacy.curseforge.com/minecraft/mc-mods/modernfix) causing mtps and tps to spike in a server environment

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heyo Devilswarchild,

Essential has been added to the default list of clientside mods. The next time you start ServerPackCreator, and reset the list of clientside mods for your server pack config, it will be in the list of your config. 

Cheers,
Griefed
