### ISSUE TITLE
[Bug]: Neoforge support - invalid or corrupt file

### ISSUE THREAD

**Issue by Conhaque** [Griefed/ServerPackCreator#467]
### What happened?

Neoforge installer spams a invalid or corrupted file when tryes install.

### What did you expect to happen?

Detailed explanation on what you expected goes here!The neoforge server start.sh tryes to download from the wrong link i think, and when try to run the following error happens
![image](https://github.com/Griefed/ServerPackCreator/assets/52429506/a644d829-c7c9-41b6-8df3-3093681829f4)

you can find the correct link in https://neoforged.net
### Version

5.0.0-alpha.21

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heyo Conhaque,

thanks for reporting this, this does indeed look like a bug in the start scripts. I'll take a look. :)

Cheers,
Griefed

**Comment by Griefed** [comment]
The issue has been identified and a fix will be available in the next alpha-release.

Cheers,
Griefed

**Comment by Griefed** [comment]
See [5.0.0-alpha.22](https://github.com/Griefed/ServerPackCreator/releases/tag/5.0.0-alpha.22).
This release contains the fixed script which will run the correct NeoForge operations.

Cheers,
Griefed
