### ISSUE TITLE
[Bug]: .zip files not properly recognized

### ISSUE THREAD

**Issue by bootlegcirno** [Griefed/ServerPackCreator#468]
### What happened?

.zip files inputted into directory produce "Error 1" https://media.discordapp.net/attachments/823976278205661265/1147526701715304548/image.pngor 1

### What did you expect to happen?

.zip files properly recognized and formatted into a server pack

### Version

4.2.1

### Anything else you would like to add?

no

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya bootlegcirno,

thanks for opening the issue here on GitHub. No ETA on a fix, but probably Soon™.

Cheers,
Griefed

**Comment by Griefed** [comment]
Should be fixed in 4.3.0 now: https://github.com/Griefed/ServerPackCreator/releases/tag/4.3.0

**Comment by Griefed** [comment]
Due to the lack of feedback I assume this is fixed. I've tested this with a couple of archives myself and so far, everything worked as expected.

I'll close this issue, but feel free to reopen it if you discover this behaviour is not fixed.

Cheers,
Griefed
