### ISSUE TITLE
[Feature ask]: Add mod to clientside list

### ISSUE THREAD

**Issue by BlakeIsMyWaifu** [Griefed/ServerPackCreator#469]
### Whats the feature you would like to be added?

The mod [Memory Usage Screen](https://www.curseforge.com/minecraft/mc-mods/memory-usage-screen) should be added to the list of clientside only mods. 

### Anything else you would like to add?

Any additional info you would like to add?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heyooo BlakeIsMyWaifu,

thanks for the submission, I'll add it to the list of clientside-mods. :)

Cheers,
Griefed

**Comment by Griefed** [comment]
Heyo BlakeIsMyWaifu,

MemoryUsageScreen has been added to the default list of clientside mods. The next time you start ServerPackCreator, and reset the list of clientside mods for your server pack config, it will be in the list of your config. 

Cheers,
Griefed
