### ISSUE TITLE
[Bug]: Sub-directoy contents copied to parent

### ISSUE THREAD

**Issue by Xplodin** [Griefed/ServerPackCreator#470]
### Whats the improvement you would like to be made?

I run a fabric forge modpack and it seems the serverpack creator program does not like the .connector directory. It ends up spilling all its contents into /mods/ instead of keeping them in /mods/.connector.
wondering if theres a way I can filter out the directory without deleting it from my folder each launch.

I could just delete the .connector folder
or
I think itd be cool to deselect directories inside other directories from the creator.
Kinda like how Curseforge lets you when exporting.

### Anything else you would like to add?

I know this might be a bad question. But I think its a big improvement (not really needed, but would be awesome)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Xplodin,

this sounds more like a bug. The contents of a subfolder should be copied to said subfolder inside its parent at the destination. I'll take a loot later today.

As for the exclusion: This should help you out: https://wiki.griefed.de/en/Documentation/ServerPackCreator/ServerPackCreator-Help#excluding-in-a-directory-you-want-to-include

Cheers,
Griefed

**Comment by Xplodin** [comment]
awesome stuff. sorry I didnt know about the exclusions stuff.
But it is strange that mod files inside .connector got moved to mods.

**Comment by Griefed** [comment]
No worries, all is well that ends well. :)

I'll change the issue to reflect this finding.

**Comment by Griefed** [comment]
What files are inside the `.connector`-directory?

**Comment by Xplodin** [comment]
> What files are inside the `.connector`-directory?

mostly mapped jars. such as fabric mods that load on forge via sinytra connector

**Comment by Griefed** [comment]
Asking because I'd like to know where these mods come from. Usually, when installing a mod, it simply gets put inside the mods-directory. Other files and folders inside the mods-directory are then created by other mods and do therefor not need to be copied to a given server pack, as the mods handle that stuff themselve.

If you've created the folder and the files inside that yourself, let me know, as I then need to adjust the way ServerPackCreator accumulates files inside said directory.

**Comment by Xplodin** [comment]
I dont create the folder or the contents inside. The connector mods does those changes

**Comment by Griefed** [comment]
Perfect, that means the stuff inside it is created automatically. Thanks for the confirmation of my suspicion.

I'll change the behaviour so only JARs inside the base mods-directory are considered, then.

**Comment by Xplodin** [comment]
awesome, thank you for making this amazing software, it really helps. :)

**Comment by Griefed** [comment]
Thank you very much! Always good to hear that people are getting a meaningful use out of this. :)

**Comment by Griefed** [comment]
There we go.
See [4.3.1](https://github.com/Griefed/ServerPackCreator/releases/tag/4.3.1)

I'll go ahead and close this ticket. Feel free to reopen it should you encounter any other issues regarding this topic, or create a new issue.

Cheers,
Griefed
