### ISSUE TITLE
[Improvement Ask]: Add Smooth Swapping as a client-side mod

### ISSUE THREAD

**Issue by vediis** [Griefed/ServerPackCreator#471]
### Whats the improvement you would like to be made?

Hey there, hope I'm posting this in the right spot - this mod is client side only and servers will refuse to start with it included.
https://modrinth.com/mod/smooth-swapping/version/0.9.2-1.19.2
https://modrinth.com/mod/smooth-swapping/version/dF51bLry

### Anything else you would like to add?

Awesome project, thanks so much for posting :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Vediis,

you've vome to the right place. I'll it SoonTM.

Cheers,
Griefed

**Comment by Griefed** [comment]
I just checked and Smooth Swapping explicitly states that is it clientside-only, therefor it will automatically be excluded by ServerPackCreator.
Unless another mod, which is not excluded, depends on it in any way, or if you've disabled the automatic exclusion of clientside-mods.

Let me know if you've got any other mod which needs to be added to the list of clientside-mods. :)

Cheers,
Griefed
