### ISSUE TITLE
[Improvement Ask]: More Client Side Mods Being Added to server files

### ISSUE THREAD

**Issue by ModernGamingWorld** [Griefed/ServerPackCreator#472]
### What happened?

Currently here are some more mods that need to be removed from servers mod folder

BetterModsButton-v4.2.4-1.19.2-Forge (https://www.curseforge.com/minecraft/mc-mods/better-mods-button) , Not sure if there is a fabric version as well.

embeddium-0.1.6+mc1.19.2 (https://curseforge.com/minecraft/mc-mods/embeddium)

gpumemleakfix-1.19.2-1.6.jar (https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)

radon-0.8.2.jar (https://www.curseforge.com/minecraft/mc-mods/radon)

textrues_embeddium_options-0.1.1+mc1.19.2 (https://www.curseforge.com/minecraft/mc-mods/textrues-embeddium-options)

### What did you expect to happen?

These Items above added to the client blacklist

### Version

Latest

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya ModernGamingWorld,

thanks for the submission. I'll check 'em and add them somewhat Soon™

Thanks for including the CurseForge links!

Cheers,
Griefed
