### ISSUE TITLE
[Help request] After creating a Server and running the start.sh the server randomly crashes after running "runJavaCommand() {   "$JAVA" ${1} }"

### ISSUE THREAD

**Issue by emilb666** [Griefed/ServerPackCreator#474]
So Server works most of the time but when it runs line 53
```
runJavaCommand() {
  "$JAVA" ${1}
}
```
it says killed 512 ish entities and then it crashes and force restarts. 
This is just from using the start.sh i have no clue what it is since logs say nothing except this

### Anything else you would like to add?

Using latest 4.3.1 release

sorry quite new with using github so please excuse error in usage
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya emilb666,

could you please provide the `start.sh` as well as the `variables.txt` file created by ServerPackCreator. Also, please provide the `latest.log` from the logs-directory of the server, if it exists.

Cheers,
Griefed

**Comment by Griefed** [comment]
> sorry quite new with using github so please excuse error in usage

No worries! We all gotta start somewhere. :) 

You can simply drag and drop the files into the comment field and then submit said comment via the `Comment`-button.
[text.txt](https://github.com/Griefed/ServerPackCreator/files/12859365/text.txt)
 Like this:

**Comment by emilb666** [comment]
oh ye also its running in a docker container if that has something to do with it

**Comment by emilb666** [comment]
[2023-10-10-1.log](https://github.com/Griefed/ServerPackCreator/files/12859837/2023-10-10-1.log)
these are the server logs 15min before crash. the container isnt stopping so the server is just restarting so which like you said might just be a mod issue

**Comment by Griefed** [comment]
It does look like your server is having a little trouble there. I'm used to seeing the occasional `moved too quickly`, especially on heavily modded servers, but your server is saying that quite often.
It's also regularly behind on ticks, with values between 2s and 8s.

As the server itself is running, at least until it crashes, this is not a ServerPackCreator related issue.

Though I'll be happy to take a look at the log at the time around a crash when you can provide one.
As for this issue, I'll go ahead and close it. 
Feel free to post the crash-log when you got one.

Until then. Happy issue-hunting, good luck and
Cheers,
Griefed
