### ISSUE TITLE
[Bug]: Systemd seems to have issues launching the start script

### ISSUE THREAD

**Issue by DisruptionSystemsINC** [Griefed/ServerPackCreator#478]
### What happened?

It seems like, starting servers via the start.sh script via a systemd service, just throws an error in systemd

Mind you, this only happens specifically when started via a systemd Service, not when manually cd-ing into a directory and running ./start.sh
My service setup is as follows:

`[Unit]
Description=Create Stellar Server
After=network.target

[Service]
User=disruption
ExecStart=/home/disruption/Create_Stellar/start.sh
Restart=on-failure
[Install]
WantedBy=multi-user.target`

The user is the main user of the system, therefore also has the neccessary permissions to access the files inside the directory. The st art.sh has been giving the executeable attribute via chmod +x

### What did you expect to happen?

Server should start as usual

### Version

4.3.0

### Relevant log output

```shell
Oct 29 18:18:02 node01 java[39918]: Error: Unable to access jarfile server.jar
Oct 29 18:18:02 node01 systemd[1]: CreateServerStarter.service: Main process exited, code=exited, status=1/FAILURE
Oct 29 18:18:02 node01 systemd[1]: CreateServerStarter.service: Failed with result 'exit-code'.
Oct 29 18:18:03 node01 systemd[1]: CreateServerStarter.service: Scheduled restart job, restart counter is at 1.
Oct 29 18:18:03 node01 systemd[1]: Stopped Create Stellar Server.
Oct 29 18:18:03 node01 systemd[1]: Started Create Stellar Server.
Oct 29 18:18:03 node01 java[39920]: Error: Unable to access jarfile server.jar
Oct 29 18:18:03 node01 systemd[1]: CreateServerStarter.service: Main process exited, code=exited, status=1/FAILURE
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heyoo,

does this still happen when you set the working directory to the same directory containing the script and server pack, i.e.:

```bash
[Unit]
Description=Create Stellar Server
After=network.target

[Service]
User=disruption
WorkingDirectory=/home/disruption/Create_Stellar
ExecStart=/home/disruption/Create_Stellar/start.sh
Restart=on-failure
[Install]
WantedBy=multi-user.target
```

**Comment by DisruptionSystemsINC** [comment]
Oh yeah, Sorry my fault^^"

**Comment by Griefed** [comment]
No worries! I take it this resolved the issue for you?
That's good to know. Happy server packing, and please do not hesitate to open another issue if you encounter anything else.

Until then.
Cheers,
Griefed
