### ISSUE TITLE
[Improvement Ask]: Ping Wheel isn't a client-side mod

### ISSUE THREAD

**Issue by RXJpaw** [Griefed/ServerPackCreator#480]
### Whats the improvement you would like to be made?

Hello! Co-Author of [Ping-Wheel](https://github.com/LukenSkyne/Minecraft-Ping-Wheel) here.

It has come to our attention that files starting with "Ping-" aren't included in Server Modpacks.
Ping Wheel is a mod that is also needed server-side to distribute pings correctly.

We had many reports of our mod not working in their modpacks because of this.
Our filename scheme: Ping-Wheel-{mod-version}-{loader-name}-{mc-version}.jar

Thank you for your time!

### Anything else you would like to add?

I haven't seen a template that fits my problem better than "Improvement Ask" sorry if this wasn't the right approach to contacting you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heyoo,

congrats! You're the very first person (that I know of) to be hit by this problem.
Someone was bound to be hit by a false-positive at some point.

I'll find a solution to this Soon™ :)

Cheers,
Griefed

**Comment by Griefed** [comment]
Oh and before I forget: You chose the correct template for this issue. This is ineed an improvement for ServerPackCreator.

I'm in the process of implementing a whitelist which will contain `Ping-Wheel-`. This will ensure that Ping Wheel will always be included if it is present in a given mod-list. 

Cheers,
Griefed

**Comment by Griefed** [comment]
There we go: https://github.com/Griefed/ServerPackCreator/releases/tag/5.0.0-beta.13

As of that version, going forward every server pack generated with ServerPackCreator will have `Ping-Wheel-` included as per the whitelist.

Version 5 will go full release Soon™, so future packs will hopefully cause you less and less trouble.

Sorry for the inconvenience!

Cheers,
Griefed
