### ISSUE TITLE
[Improvement Ask]: Add Distant Horizons to the fallback-list

### ISSUE THREAD

**Issue by tecrogue** [Griefed/ServerPackCreator#482]
### Whats the improvement you would like to be made?

I would like the following mods to be added to the fallback-modslist

-  Distant Horizons https://legacy.curseforge.com/minecraft/mc-mods/distant-horizons

### Anything else you would like to add?

Really appreciate all the work that has been done so far!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heyo,

Distant Horizons is already present on the clientside-only list:

- https://github.com/Griefed/ServerPackCreator/blob/1a75123826646fb28bdd46d7d7738acdad9bf93a/serverpackcreator-api/src/jvmMain/kotlin/de/griefed/serverpackcreator/api/ApiProperties.kt#L170
- https://github.com/Griefed/ServerPackCreator/blob/1a75123826646fb28bdd46d7d7738acdad9bf93a/serverpackcreator-api/src/jvmMain/resources/serverpackcreator.properties#L4 (search for `Distant`)

If the clientside list of your server pack config doesn't have said mod in it, you need to reset it. You can use this button ![grafik](https://github.com/Griefed/ServerPackCreator/assets/44273438/93ca25f1-545d-4c86-bd3a-653076c1f010) next to the area of clientside mods to do so. Just be aware that any manually added mods will be removed by this action. 

Cheers,
Griefed
