### ISSUE TITLE
[Bug]: -web arg does not work

### ISSUE THREAD

**Issue by AzureDoom** [Griefed/ServerPackCreator#484]
### What happened?

Testing with `java -jar serverpackcreator.jar -web` does not start the webserver

### What did you expect to happen?

Web server starts up

### Version

5.1.3

### Anything else you would like to add?

It looks to run the program itself simply. Running `java -jar serverpackcreator.jar -help` and using the option there does attempt to start webserver

### If you are using the webservice, in which browers did you encounter this bug?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Whilst I work on #485 please note that ServerPackCreator version 5=< requires Java 21 to run.

**Comment by AzureDoom** [comment]
> Whilst I work on #485 please note that ServerPackCreator version 5=< requires Java 21 to run.

Yup! Found that when first testing, so I'm using Java 21

**Comment by Griefed** [comment]
Please try again using [5.1.5](https://github.com/Griefed/ServerPackCreator/releases/tag/5.1.5).

**Comment by AzureDoom** [comment]
Still no luck, still have to access it via the -help method.

**Comment by Griefed** [comment]
You're trying to run the webservice using the .jar-file, right?

**Comment by Griefed** [comment]
I'm afraid I can not reproduce this.

- created an Ubuntu 20.04LTS VM
- downloaded a Java 21 JDK from [Adoptium](https://adoptium.net/de/temurin/releases/?os=linux&arch=x64&package=jdk&version=21)
- downloaded ServerPackCreator 5.1.5
- moved everything to the root-user as you did in https://github.com/Griefed/ServerPackCreator/issues/485#issue-2034375202
- ran `jdk21/bin/java -jar ServerPackCreator-5.1.5.jar -web`

The webservice came up. Though the issue you described in https://github.com/Griefed/ServerPackCreator/issues/485#issuecomment-1849578379 still remains, somehow.

**Comment by AzureDoom** [comment]
Hmm yeah, not sure then, no biggy here since I can access via the help menu. so I don't mind the extra step at all. I'll close for now since you can't reproduce this and we'll keep to the 485 issue.
