### ISSUE TITLE
[Bug]: NeoForge 1.20.2+ fails to find Installer files

### ISSUE THREAD

**Issue by AzureDoom** [Griefed/ServerPackCreator#486]
### What happened?

Try to set Minecraft version to 1.20.2+ with NeoForge selected, a pop-up appears stating it couldn't find the installer. 

### What did you expect to happen?

NeoForge installers would be found.

### Version

5.1.3

### Anything else you would like to add?

In case you need the download location for NeoForges installers, they can be found here until their website is updated: https://maven.neoforged.net/#/releases/net/neoforged/neoforge/

20.2.x is 1.20.2
20.3.x is 1.20.3
20.4.x is 1.20.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
ServerPackCreator appears to be able to find things for NeoForge 1.20.1 no problem. However, newer versions appear to cause trouble.

Sure enough, NeoForge provides no data for 1.20.2 and up:

Source: https://maven.neoforged.net/releases/net/neoforged/forge/maven-metadata.xml

```xml
<metadata>
<groupId>net.neoforged</groupId>
<artifactId>forge</artifactId>
<versioning>
<latest>1.20.1-47.1.81</latest>
<release>1.20.1-47.1.81</release>
<versions>
<version>1.20.1-47.1.7</version>
<version>1.20.1-47.1.5</version>
<version>1.20.1-47.1.8</version>
<version>1.20.1-47.1.9</version>
<version>1.20.1-47.1.11</version>
<version>1.20.1-47.1.12</version>
<version>1.20.1-47.1.23</version>
<version>1.20.1-47.1.25</version>
<version>1.20.1-47.1.26</version>
<version>1.20.1-47.1.27</version>
<version>1.20.1-47.1.28</version>
<version>1.20.1-47.1.54</version>
<version>1.20.1-47.1.55</version>
<version>1.20.1-47.1.56</version>
<version>1.20.1-47.1.57</version>
<version>1.20.1-47.1.58</version>
<version>1.20.1-47.1.59</version>
<version>1.20.1-47.1.60</version>
<version>1.20.1-47.1.61</version>
<version>1.20.1-47.1.62</version>
<version>1.20.1-47.1.63</version>
<version>1.20.1-47.1.64</version>
<version>1.20.1-47.1.65</version>
<version>1.20.1-47.1.66</version>
<version>1.20.1-47.1.67</version>
<version>1.20.1-47.1.69</version>
<version>1.20.1-47.1.70</version>
<version>1.20.1-47.1.71</version>
<version>1.20.1-47.1.72</version>
<version>1.20.1-47.1.73</version>
<version>1.20.1-47.1.74</version>
<version>1.20.1-47.1.75</version>
<version>1.20.1-47.1.76</version>
<version>1.20.1-47.1.77</version>
<version>1.20.1-47.1.78</version>
<version>1.20.1-47.1.79</version>
<version>1.20.1-47.1.80</version>
<version>1.20.1-47.1.81</version>
</versions>
<lastUpdated>20231130232248</lastUpdated>
</versioning>
</metadata>
```

Aaaaaaaand it's because they moved their manifests. Lovely.
The new one is at https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml

That's gonna take some time to solve.

**Comment by Griefed** [comment]
Not directed at you.

I'd love to take a moment and offer a giant F-you to the modloader community for creating this clusertruck of an environment that is Forge, NeoForge, Fabric, Quilt, LegacyFabric and anything else.

**Comment by AzureDoom** [comment]
> ServerPackCreator appears to be able to find things for NeoForge 1.20.1 no problem. However, newer versions appear to cause trouble.
> 
> Sure enough, NeoForge provides no data for 1.20.2 and up:
> 
> Source: https://maven.neoforged.net/releases/net/neoforged/forge/maven-metadata.xml
> 
> ```xml
> <metadata>
> <groupId>net.neoforged</groupId>
> <artifactId>forge</artifactId>
> <versioning>
> <latest>1.20.1-47.1.81</latest>
> <release>1.20.1-47.1.81</release>
> <versions>
> <version>1.20.1-47.1.7</version>
> <version>1.20.1-47.1.5</version>
> <version>1.20.1-47.1.8</version>
> <version>1.20.1-47.1.9</version>
> <version>1.20.1-47.1.11</version>
> <version>1.20.1-47.1.12</version>
> <version>1.20.1-47.1.23</version>
> <version>1.20.1-47.1.25</version>
> <version>1.20.1-47.1.26</version>
> <version>1.20.1-47.1.27</version>
> <version>1.20.1-47.1.28</version>
> <version>1.20.1-47.1.54</version>
> <version>1.20.1-47.1.55</version>
> <version>1.20.1-47.1.56</version>
> <version>1.20.1-47.1.57</version>
> <version>1.20.1-47.1.58</version>
> <version>1.20.1-47.1.59</version>
> <version>1.20.1-47.1.60</version>
> <version>1.20.1-47.1.61</version>
> <version>1.20.1-47.1.62</version>
> <version>1.20.1-47.1.63</version>
> <version>1.20.1-47.1.64</version>
> <version>1.20.1-47.1.65</version>
> <version>1.20.1-47.1.66</version>
> <version>1.20.1-47.1.67</version>
> <version>1.20.1-47.1.69</version>
> <version>1.20.1-47.1.70</version>
> <version>1.20.1-47.1.71</version>
> <version>1.20.1-47.1.72</version>
> <version>1.20.1-47.1.73</version>
> <version>1.20.1-47.1.74</version>
> <version>1.20.1-47.1.75</version>
> <version>1.20.1-47.1.76</version>
> <version>1.20.1-47.1.77</version>
> <version>1.20.1-47.1.78</version>
> <version>1.20.1-47.1.79</version>
> <version>1.20.1-47.1.80</version>
> <version>1.20.1-47.1.81</version>
> </versions>
> <lastUpdated>20231130232248</lastUpdated>
> </versioning>
> </metadata>
> ```
> 
> Aaaaaaaand it's because they moved their manifests. Lovely.
> The new one is at https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml
> 
> That's gonna take some time to solve.

Ah yeah, it makes sense that it's moved since 1.20.2 was the big break away compatibility wise from Forge and they renamed all the internals to neoforged.

**Comment by Griefed** [comment]
NeoForge is testing my patience: https://github.com/Griefed/ServerPackCreator/issues/489

Haven't had the time to to work on this issue, yet, as the webservice fix has a higher priority for me, personally.

**Comment by AzureDoom** [comment]
Lol its no problem, I'm in no rush
