### ISSUE TITLE
[Feature ask]: Web Server Port Configuration

### ISSUE THREAD

**Issue by AzureDoom** [Griefed/ServerPackCreator#487]
### Whats the feature you would like to be added?

Configuration value for the port that the web server would run on.

### Anything else you would like to add?

This is primarily a feature request as to be able to run multiple instances of the SPC from the same machine/IP.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heyo,

try setting `server.port=8080` in the `serverpackcreator.properties`.
That should change the listening port for the webservice.

**Comment by AzureDoom** [comment]
I assume that's one I set manually? Notice it's not a default one but testing now!

**Comment by AzureDoom** [comment]
Yup, that works perfectly! Thanks again!

**Comment by AzureDoom** [comment]
> What do you mean by `Notice it's not a default one`? From my experience, port 8080 is pretty much a default one to prevent clashes with port 80.

Not a default configuration option is what I meant, sorry, but simply adding that line worked for it as I wanted to move to other ports to run more than one instance once the web panel issue is fully sorted. I plan in running 3 instances so being able to with different ports/folders will help me a ton!
