### ISSUE TITLE
[Improvement Ask]: Add ability to create pack without run scripts and jvm arguments.

### ISSUE THREAD

**Issue by Ianthasys** [Griefed/ServerPackCreator#488]
### Whats the improvement you would like to be made?

Personally, I use the pack creator to remove client-side dependencies when I update whatever modpack I'm running on my server. It would be nice to be able to have the creator skip making run scripts and java args file, as I'm just reusing the ones created by the docker container I'm already using for the pack. (the ones created by the docker container don't have the same naming scheme as the ones made by SPC, so they just take up extra space on the drive.) As of currently, I just delete them myself after unzipping, but it'd be nice if they weren't created in the first place as it's less data to upload to the server over ssh.

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Additionally
> it's less data to upload to the server over ssh.

They're very small textfiles. If you worry about a couple of Kb's of data, you have much bigger problems at hand than my script- and variables-files. It's hardly worth mentioning.

**Comment by Ianthasys** [comment]
it's not like it was an urgent thing. as I said, I just delete them myself. it'd be nice to be able to not have them created in the first place though. given that there's a checkbox to include server icon and properties, I figured it wouldn't be a bad idea to have a fourth box that left out the run scripts.
![image](https://github.com/Griefed/ServerPackCreator/assets/100318148/211000b9-6a78-4555-8c31-31b6aabbb195)

**Comment by Ianthasys** [comment]
Given that you said it'd be much more work than necessary, I'll close the issue though.

**Comment by Griefed** [comment]
Aye, it'd be much more work compared to `rm file`, in addition to the fact that the vast majority of people generate server packs for distribution on platforms like CurseForge or Modrinth, where the people who download these packs simply want to run the script and be done with it.

I appreciate the fact that you took the time to create this issue, but I have to decline this one.

Take care o7
