### ISSUE TITLE
[Documentation]: Possible values for "modLoader" are listed as only Forge and Fabric

### ISSUE THREAD

**Issue by CataclystP** [Griefed/ServerPackCreator#490]
### Which documentation would you like to be updated?

in [the documentation](https://wiki.griefed.de/en/Documentation/ServerPackCreator/ServerPackCreator-Help), the description for "modLoader" under the Configuration section says that the value of "modLoader" should either be Forge or Fabric, even though current accepted values are "Forge", "NeoForge", "Fabric", "Quilt" and "LegacyFabric".

### Anything else you would like to add?

Nothing specific to add.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heyo,

thanks for the pointer! I fixed the wiki entry. :)
