### ISSUE TITLE
[Bug]: -cgen has options listed incorrectly when editing a configuration file

### ISSUE THREAD

**Issue by CataclystP** [Griefed/ServerPackCreator#492]
### What happened?

when using -cgen, and configuring through CLI, the listed actions one can perform are out of order and are sometimes missing. of note are the following:
(6): which changes the minecraft version of your pack.
(7): which changes the mod loader (also linked with #491) for your pack.
(8): which changes the version of the modloader for your pack.
(9): which changes whether to include a server-icon.png in your pack.
(10): which changes whether to include a server.properties in your pack.
(11): which changes whether to create a zip-archive of your pack.
(12): which changes your java arguments for your pack.
(13): which changes the suffix of your pack.
(14): which saves the current configuration to a seperate file.
(15,16,17,18): which print the current configuration.

missing are:
- the option to change the whether to install the modloader server during pack generation (listed as 6)
- the option to change the java installation for the pack (listed as 10)
- the option to check the current configuration (listed as 18)

### What did you expect to happen?

the listed actions to match with what the options do in actuality.

### Version

5.1.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heyo,
thanks for the report! The option to install the modloader server via ServerPackCreator was removed a couple of updates ago. I forgot to edit the CLI menu accordingly. A fix will be rolled out together with a fix for https://github.com/Griefed/ServerPackCreator/issues/491

Cheers,
Griefed
