### ISSUE TITLE
[Documentation]: add a section explaining the behaviour and format of [[inclusions]] in the .conf file

### ISSUE THREAD

**Issue by CataclystP** [Griefed/ServerPackCreator#494]
### Which documentation would you like to be updated?

The documentation is missing a section explaining how to change and modify the [[inclusions]] section of the .conf file. While these are intended to be edited via the CLI, GUI, or webserver, it would still be nice to document how it should look in the INI(?) file just in case manual edits are needed/or are preferred by some users.

### Anything else you would like to add?

:3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CataclystP** [comment]
I cant seem to add the enhancement label myself otherwise I would have.

**Comment by Griefed** [comment]
That's alright. This is definitely a documentation issue. 🙂
