### ISSUE TITLE
[Improvement Ask]: Add MinecraftCapes to the Mod-Exclusions

### ISSUE THREAD

**Issue by MoonstruckDev** [Griefed/ServerPackCreator#495]
### Whats the improvement you would like to be made?

MinecraftCapes is a client side mod and from what I can see it's not in exclusions

I don't think making a PR for one singular mod is a great thing so i'll put this as an ask

### Anything else you would like to add?

[Link To The Mod on CF](https://www.curseforge.com/minecraft/mc-mods/minecraftcapes-mod)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
MinecraftCapes has been added to the default list of clientside-only mods. Reset any list of your server pack configurations to receive this new list.

Thanks for the report!

Cheers,
Griefed
