### ISSUE TITLE
[Improvement Ask]: Add REI Plugin Compatabilities and YUNG's Menu Tweaks (Forge) to the fallback list

### ISSUE THREAD

**Issue by Elrol** [Griefed/ServerPackCreator#500]
### Whats the improvement you would like to be made?

I would like the following mods to be added to the fallback-modslist:

REI Plugin Compatabilities: [https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks)
YUNG's Menu Tweaks: [https://www.curseforge.com/minecraft/mc-mods/yungs-menu-tweaks](https://www.curseforge.com/minecraft/mc-mods/yungs-menu-tweaks)

### Anything else you would like to add?

Both of the mods cause issues on the server unless they are removed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya Elrol,

is REI Plugin Compatibilities (REIPC) actually a clientside-only mod? I'm seeing no hints to it being exclusively clientside so far.

**Comment by Griefed** [comment]
YUNG's Menu Tweaks has been added to the clientside-mods list. :)

**Comment by Elrol** [comment]
At first, it had been throwing errors while my server was crashing, i
removed both and it started up. So I had thought they both were the cause,
but I currently have REIPC running on the server so its not a client onlu
mod

**Comment by Griefed** [comment]
Alrighty, thanks for clearing that up. I consider this issue done, then. :)

Cheers,
Griefed
