### ISSUE TITLE
[Bug]: colon between the libs?

### ISSUE THREAD

**Issue by Norisek** [Griefed/ServerPackCreator#505]
### What happened?

I can't start server, because of illegal character, but it's past windows path.

### What did you expect to happen?

Server launches normally.

### Version

5.1.10

### Relevant log output

```shell
Start script generated by ServerPackCreator 5.1.10.
To change the launch settings of this server, such as JVM args / flags, Minecraft version, modloader version etc., edit the variables.txt-file.

Running Forge checks and setup...
Generating user_jvm_args.txt from variables...
Edit JAVA_ARGS in your variables.txt. Do not edit user_jvm_args.txt directly!
Manually made changes to user_jvm_args.txt will be lost in the nether!
libraries/net/minecraftforge/forge/1.19.2-43.3.7/forge-1.19.2-43.3.7-server.jar present.

libraries/net/minecraft/server/1.19.2/server-1.19.2.jar present.


Starting server...
Minecraft version: 1.19.2
Modloader:         Forge
Modloader version: 43.3.7

Java args:         -Xms6G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true
Java path:         java
Run Command:       java -Dlog4j2.formatMsgNoLookups=true @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.2-43.3.7/unix_args.txt nogui
Java version:
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

Error occurred during initialization of boot layer
java.nio.file.InvalidPathException: Illegal char <:> at index 70: libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar:libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar:libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar:libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar:libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar:libraries/org/ow2/asm/asm/9.5/asm-9.5.jar:libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar

Exiting...
Press any key to continue
```

### Anything else you would like to add?

Tell me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heya,

errors like this may be caused by paths with spaces in them when running a server on Windows. Its a Powershell issue I have no control over. Or it may be an issue with Forge. Either way, this is, unfortunately for you, not a ServerPackCreator issue/bug.

Just to be on the safe side: You mentioned 
> past windows path

You are using Windows and you ran the .ps1-script, correct?

Cheers,
Griefed

**Comment by Norisek** [comment]
> You are using Windows and you ran the .ps1-script, correct?

Yes and yes.

I said "past windows path" because it looks as if the illegal character was inside the jar file according to the path from the error.

**Comment by Griefed** [comment]
If the invalid character was inside the JAR, then there'd be nothing I could do about it, as that portion of the start procedure already concerned the Forge server.

The only thing I could imagine being an issue would be spaces or special characters inside the path to the server pack.

**Comment by Griefed** [comment]
It's recently come to my attention that the way a Powershell script is started may also have an affect on running it.

Unless you're already doing it that way, then:
- Open a Powershell window
- Navigate to the folder where your server pack resides in
- run `.\start.ps1`

If this also doesn't help, then I'm out of ideas.

Cheers,
Griefed

**Comment by Griefed** [comment]
Closing this due to lack of feedback. Feel free to re-open if this pops up again. Keep in mind, though, that the described behaviour is nothing I can do much about, as I already explained how to handle it.

Cheers,
Griefed
