### ISSUE TITLE
LocalizationManager: add falling back to English (US) when localization key doesn't exist in current language file

### ISSUE THREAD

**Issue by whitebear60** [Griefed/ServerPackCreator#51]
@Griefed Assign me to this, I will try to get rid of this in a few days.

**Comment by Griefed** [comment]
Alrighty, good luck!

**Comment by Griefed** [comment]
Available as of 
- https://github.com/Griefed/ServerPackCreator/commit/5802636a612c4a49878f68b827e1115895062a95
- https://github.com/Griefed/ServerPackCreator/commit/802eb0c5a4aa06b90d71bb570864bcda613bc55c
