### ISSUE TITLE
[Improvement Ask]: Client-side mod blacklists:

### ISSUE THREAD

**Issue by muon-rw** [Griefed/ServerPackCreator#511]
### Whats the improvement you would like to be made?

lazurite-
EuphoriaPatcher-
citresewn-
SuperBetterGrass-

### Anything else you would like to add?

Edit: Mod links
https://modrinth.com/mod/lazurite
https://modrinth.com/mod/euphoria-patches
https://modrinth.com/mod/cit-resewn
https://www.curseforge.com/minecraft/mc-mods/super-better-grass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
CITRespawn and SuperBetterGrass define themselves as clientside-only, thus they can be automatically excluded. 

Lazurite and Euphoria Patches have been added. They will be available once the current alpha-beta branches will be merged into main. :) Until this happens, I will leave this issue open.

Thanks!

Cheers,
Griefed

**Comment by Griefed** [comment]
Available as of [5.1.12](https://github.com/Griefed/ServerPackCreator/releases/tag/5.1.12)

Thanks for the submissions!

Cheers,
Griefed
