### ISSUE TITLE
[Clientside-mod Addition Request]: ItemLocks

### ISSUE THREAD

**Issue by muon-rw** [Griefed/ServerPackCreator#524]
### The link to the project on CurseForge or Modrinth

https://www.curseforge.com/minecraft/mc-mods/itemlocks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Griefed** [comment]
Heyo,

ItemLocks is already present:

https://github.com/Griefed/ServerPackCreator/blob/759c8b777066b244c2c89a4a00eb62e09fd93c04/serverpackcreator-api/src/jvmMain/kotlin/de/griefed/serverpackcreator/api/ApiProperties.kt#L237

https://github.com/Griefed/ServerPackCreator/blob/759c8b777066b244c2c89a4a00eb62e09fd93c04/serverpackcreator-api/src/jvmMain/resources/serverpackcreator.properties#L5

If it's still included in your server packs, then you probably haven't reset the clientside-list for the individual server pack config yet. Check out the *Advanced*-section at the bottom of ServerPackCreators server pack config screen, and use the buttons on the right to reset it to the default one.

Cheers,
Griefed

**Comment by muon-rw** [comment]
Seems like it works - apologies for not double checking beforehand!

**Comment by Griefed** [comment]
Yeah I saw the conversations on the Lunar Pixel Discord and was beginning to doubt myself. 😓 
Glad that it worked out!

Let me know if you encounter anything else.

Cheers,
Griefed
