### ISSUE TITLE
select mod loader needs to sort down like select mc version does

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#74]
* **What is the current behavior?**

select mod loader lists oldest mod loader first and most current last, which is opposite of the mc versions drop-down.
* **What is the wanted/requested behavior?**

select mod loader list should show the most recent or latest on the top and the sort down towards the oldest. Also the most recent should be auto-selected the first time this feature is accessed on a new server pack build.
* **What are your reasons for making this feature request? Provide solid arguments on why I should start working on it.**
The most solid argument I can make is "convenience". By not having to scroll to the bottom of the list for the most recent modloader version of fabric or forge.

**This** has existed in all versions since the drop down lists were implemented to include the alpha you released on the 27th.

**Comment by Griefed** [comment]
Thanks for using the template! 😁
100% agree and I am already working on reversing the order of the lists so the newest version is at the top of each list respectively. 🙂

**Comment by Griefed** [comment]
Will be available in the next alpha release. 🙂

**Comment by Griefed** [comment]
See https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.2 🙂
