### ISSUE TITLE
Field for Version Numbering for Packs

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#77]
* **What is the current behavior?**
 Currently server packs are just the name of the pack and the words “server_pack”.

* **What is the wanted/requested behavior?**

Have an extra field on the form where I can specify the pack version so that it can be included in the server packs filename.

* **What are your reasons for making this feature request? Provide solid arguments on why I should start working on it.**
When I'm uploading packs, i don't have to rename them to reflect the version of the client pack, as it will already be done for me based on that version field. 

* **Not asking for specialized incremental mechanics**
I wouldn't recommend going beyond that, it'd be nice if it remembered itself, but then that's up to me to save the config each time. Furthermore, because many individuals have different versioning schemes, that's why I think a plain old field is more than sufficient. :)

**Comment by Griefed** [comment]
Heya,

Thanks for the frature request. Any preferences on where in the GUI this should be placed?

Cheers,
Griefed

**Comment by kreezxil** [comment]
maybe squish up the first line where the mod pack path lives. that would be
a great place for it.

**Comment by Griefed** [comment]
Sounds good to me.

**Comment by Griefed** [comment]
Just started working on this. Just a heads up, the suffix will *not* be stored in the configfile, as it will most likely either
- not be used be a given user
- change with every server pack a user generates for a given version of their modpack

So I won't be storing the last configuration anywhere and the textfield for the suffix will be blank everytime you start SPC.

**Comment by Griefed** [comment]
Looking good to you? 
![image](https://user-images.githubusercontent.com/44273438/134055609-badebfec-cf56-42d0-99a6-e912abd91faa.png)

**Comment by Griefed** [comment]
I'll take that as a yes :D 
Will be available in the next alpha.

**Comment by kreezxil** [comment]
I was thinking the suffix should be stored. Or in your master config, allow us to set whether it gets stored. That would be advantageous to me, as I'm making on avg of at least a server pack every two days or more. It saves having to look up the last version number I used on a pack, as it would already be there. And yes, I save out the config for each pack to their own separate config file, so I can easily reload them. Keep in mind, I have 62 mod pack snow.

**Comment by Griefed** [comment]
> I have 62 mod pack snow.

You. Absolute. Madman.
I'll have a think about it. 🙂

**Comment by Griefed** [comment]
Will be available in the next alpha. 
The suffix will be stored like this:

```
# Suffix to append to the server pack to be generated. Can be left blank/empty.
serverPackSuffix = "foobar"
```

**Comment by Griefed** [comment]
Available as of [3.0.0-alpha.6](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.6).

**Comment by kreezxil** [comment]
after using it a bit I realize it needs to auto-prepend a hyphen, else i"m
typing a hyphen to avoid world-of-dragons-II4.7.8 instead of
world-of-dragons-II-4.7.8

**Comment by Griefed** [comment]
You can just add a hyphen to the suffix? I wanted to give the user full control over the suffix, hence no auto-prepend of anything.
