### ISSUE TITLE
Status Needs to be cleaner.

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#79]
* **What is the current behavior?**

The status line that appears at the bottom of the app while server pack is being built could use some cleaning of extraneous characters.

* **If the current behavior is a bug, please provide the steps to reproduce**

make a server pack

* **What is the expected behavior?**

clean status line

* **Please tell us about your environment:**

- Your Operating System: Manjaro KDE Plasma
- Your Java version: java 11
- Your ServerPackCreator version:the about box doesn't show the version, i download the September 22nd version from the ci/cd pipeline. 
- Your config file:  https://gist.github.com/98b738e1b005595de9a6f05fe1462e73
- My properties file: https://gist.github.com/c81f195dbad63ba4dec611abd7c2198e
- Your latest log file: 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

what the status line looks like for me.
![image](https://user-images.githubusercontent.com/3880072/134675796-10891f62-506b-472a-b30a-771b5665f764.png)

**Comment by Griefed** [comment]
I mean, running Alpha3
![image](https://user-images.githubusercontent.com/44273438/134677265-ab540aba-fec1-4350-963c-758ad67d0b9c.png)

Could be something OS related. Has this always been an issue for you when running on Linux?

**Comment by Griefed** [comment]
Tested it with the testbuild you mentioned (which doesn't have a version because it's from a testbuild) and that displays the status correctly on Windows as well. Might really be Linux-related.

**Comment by kreezxil** [comment]
yeah it's been like this on Linux the entire time.

**Comment by kreezxil** [comment]
Probably some ANSI sequences not being interpreted right

**Comment by Griefed** [comment]
Huh. Strange. Could you send me the `serverpackcreator.log`-file in question and check whether your `log4j2.xml`-file contains the following configuration for the `serverpackcreator.log`:

```xml
<RollingFile name="ApplicationLogger" fileName="${log-path}/serverpackcreator.log" filePattern="${archive}/serverpackcreator.log.%i">
    <PatternLayout>
        <Pattern>
            ${pattern}
        </Pattern>
    </PatternLayout>
    <Policies>
        <OnStartupTriggeringPolicy />
        <SizeBasedTriggeringPolicy size="10 MB" />
    </Policies>
    <DefaultRolloverStrategy max="5" />
</RollingFile>
```

Especially the `<Pattern>[...]</Pattern>`-part is important here. Said pattern should be:
```xml
<Property name="pattern">%d{ISO8601} %5p [%t] (%F:%L) - %m%n</Property>
```

**Comment by Griefed** [comment]
Can you try with this [log4j2.xml](https://gist.github.com/Griefed/5653a9868d2f9ce268dc9cc16da6d2ef)? This sets the charset to UTF-8. UTF-8 is used by default if it is not specified, but it's a start.

Also, I've tested with alpha5 in an Ubuntu 20.04 LTS VM running GNOME and for whatever reason the status looks fine for me here as well:
![image](https://user-images.githubusercontent.com/44273438/134761240-4f530c60-044f-4772-978e-462fb1eb290f.png)

**Comment by kreezxil** [comment]
Yes! That resolves the problem. Thank you! :)

**Comment by Griefed** [comment]
Awesome! That's a relieve! Thanks for the feedback. 🙂 I find it rather strange that explicitly setting it to UTF-8 seemed to do the trick, even though according to log4j-documentation that's what's the default value if none is specified, but oh well.
