### ISSUE TITLE
Feature: argument to walk user through config setup

### ISSUE THREAD

**Issue by Griefed** [Griefed/ServerPackCreator#8]
Run spc with setup in cli to help user setup correct config step by step

**Comment by Griefed** [comment]
@whitebear60 and I will both start working on this issue as this is new territory to both of us.

**Comment by Griefed** [comment]
Note: Can not assign whitebear60 because reasons? (GitHub, what are you doing?)

**Comment by whitebear60** [comment]
Don't know, I can't modify project config files, I can't work with assignees too, I can just unassign me when I asigned to something.

**Comment by Griefed** [comment]
Aha, people need to comment on the relevant issue in order for them to be assignable. Assigned us both to this.

**Comment by Griefed** [comment]
Considering this feature complete with https://github.com/Griefed/ServerPackCreator/commit/bf79e981c879495ea51e636e3c4d655038821aa6
