### ISSUE TITLE
Bug: Start scripts for Forge contain wrong nogui parameter

### ISSUE THREAD

**Issue by Griefed** [Griefed/ServerPackCreator#82]
* **What is the current behavior?**

Using the genersted start scripts for Forge fails, because it tried to run `--nogui` when it should run `nogui` instead.

The error is in `ServerPackHandler.class` with the `--nogui` ending in the String definition.

* **If the current behavior is a bug, please provide the steps to reproduce**

* Generate a server pack for Forge
* Let ServerPackCreator generate start scripts
* Use said start scripts

* **What is the expected behavior?**

The start scripts should start the server.

* **Please tell us about your environment:**

- Your Operating System: Any
- Your Java version: Any
- Your ServerPackCreator version: Alpha.6
- Your config file:  
- Your latest log file: 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Griefed** [comment]
So, running some tests yielded interesting results:

Running with `--nogui` worked on both **Windows** and **Linux**
Running with `nogui` worked on both **Windows** and **Linux**, too!

**Comment by Griefed** [comment]
False alarm.
The issue was an incomplete Forge installation, probably due to problems on Forge's side, or some sort of internet-connection problem. The start scripts themselves were fine.

**Comment by kreezxil** [comment]
alpha.8, causes the gui to popup when run with --nogui, removing the -- makes it not come up. in all my dealings, forge didn't like the --, ie when it sees it, it ignores it.

**Comment by Griefed** [comment]
So, sometimes it likes it, sometimes it doesn't.
Which Forge version was affected in your case?

**Comment by kreezxil** [comment]
1.12.2

**Comment by Griefed** [comment]
Fixed. Will be available in the next alpha release. I removed the `--` from the `nogui` argument for Forge scripts.

**Comment by Griefed** [comment]
Available as of [3.0.0-alpha.10](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.10) 
Feel free to report any bugs. I'll close this feature request issue. 🙂

Enjoy! 👍
Cheers,
Griefed
