### ISSUE TITLE
Specifying a file to include in the server pack fails. Only directories are accepted.

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#85]
* **What is the current behavior?**

if you tell it some filenames, it'll say invalid config

* **If the current behavior is a bug, please provide the steps to reproduce**

after selecting dirs to include, type in a file to include too. like server-icon.png, it does't like that.

* **What is the expected behavior?**

to love it

* **Please tell us about your environment:**

Linux KDE

- Your Operating System: Manjaro KDE Plasma
- Your Java version: 1.8
- Your ServerPackCreator version: got it from the pipeline released on Octover 5 2021
- Your config file:  https://haste.zneix.eu/moxybimefo
- Your latest log file:  https://haste.zneix.eu/uqerosylen

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Griefed** [comment]
Did you specify the file with a destination as well? If you want to include a single file from somplace, the format is `path/to/source;path/to/destination/in/serverpack`

**Comment by kreezxil** [comment]
no i just gave it the filename, not a full path. i assume because the dirs don't use a full path, that all pathing is implied to be relative.

**Comment by Griefed** [comment]
> the gui text says explicitly that it accepts dirs and files to add.
> 
> ![image](https://user-images.githubusercontent.com/3880072/136637260-4a0c9b72-1ddc-48ba-ba21-415b8af342c0.png)

It explicity says that you can add files as well, yes, however, the tooltip states 
![image](https://user-images.githubusercontent.com/44273438/136645874-77cbce77-636d-4c2f-9639-b05c01132c10.png)

Here is an example:
![image](https://user-images.githubusercontent.com/44273438/136646043-be54da8d-3b72-4ed0-b203-e68ba0877c20.png)

Hope this helps!

Cheers,
Griefed

**Comment by Griefed** [comment]
Simple file connotations will be available in the next alpha release. See #86
