### ISSUE TITLE
Crash at install (alpha-7)

### ISSUE THREAD

**Issue by Maxwelljones** [Griefed/ServerPackCreator#87]
* **What is the current behavior?**
Crashing at start. It doesn't even download any of the assets. Tried launching the .exe and the jar file through PowerShell. None of those let it start.

* **If the current behavior is a bug, please provide the steps to reproduce**
- Download version alpha7 or 6.
- Run PowerShell in folder
- execute java -jar versionname

* **What is the expected behavior?**
Installing assets and launching the softwar.e

* **Please tell us about your environment:**
- Your Operating System: Win10
- Your Java version: 8 up.301
- Your ServerPackCreator version: alpha7 (same behaviour with alpha6)
- Your config file: (non was generated)
- Your latest log file: https://gist.github.com/Maxwelljones/d4432709bcff3da2f9880099ea96c924

* **Other information** 
Let me know if you need anymore detail, I'm happy to help.

**Comment by Griefed** [comment]
Hey Maxwelljones,

thanks for opening this issue! I'll take a look now.

Cheers,
Griefed

**Comment by Maxwelljones** [comment]
Hi there Griefed :)
Thank you so much for such a quick reaction!

To answer your questions:
The files are about 44MB each: 
![image](https://user-images.githubusercontent.com/3750700/137397294-65e000e2-25a7-494a-a3fd-7f85179e7c9e.png)
Guessing they are the right size.

On firewall and antivirus software: running comodo firewall + avast av. They are accepting the program just fine (see edit below)

Edit: I got the point.
The unusual naming convention of my folders or the path to the folder made it break somehow (possibly total length of the path exceeded or some characters not accepted in the path (like "-" or "!") ?

It now works as expected. Thank you so much for your help!

**Comment by Griefed** [comment]
Hey, glad you got it sorted out! :)

If the path contains an `!` that is most likely the cause for the problem.
The exclamation mark is used in Java URLs for accessing files inside an archive among probably other things. Example from ServerPackCreator:
- Accessing the `mods.toml`-file in a Minecraft 1.12 or newer mod. Exampe in line 1900 in ServerPackHandler.java https://github.com/Griefed/ServerPackCreator/blob/8a53aa6b9dbf148d60f4001a47e64055e8975d10/backend/main/java/de/griefed/serverpackcreator/ServerPackHandler.java#L1900
