### ISSUE TITLE
Feature request: Allow specification of server icon to include

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#88]
* **What is the current behavior?**

when selecting the server icon to be included, it always includes the default one

* **What is the wanted/requested behavior?**

use previously set server icon

* **What are your reasons for making this feature request? Provide solid arguments on why I should start working on it.**
* 
Now that, we can save and reload configs. It would be nice if it could load the previously set server-icon from the conf.

Which means, yet another field to store the absolute path to said server-icon, it would pull that one in, if it can't find it, then it would default to the one you're providing?

**Comment by Griefed** [comment]
Thank you very much!

**Comment by Griefed** [comment]
Will be available in the next alpha release. In addition to being able to specify a custom server-icon.png to include, ServerPackCreator will also scale it to 64x64. Meaning: It doesn't matter if the specified image is bigger or smaller than 64x64 pixels, the icon in the server pack will always be 64x64. ServerPackCreator rescales it. 
Now, granted, if you use an image with aspect ratios other than 1:1, it'll come out strange, but that's in the nature of scaling non-1:1 to 1:1.

**Comment by Griefed** [comment]
https://git.griefed.de/Griefed/ServerPackCreator/-/commit/e3670e4ffc15505856ae9695f59f3c614e0199dd

**Comment by Griefed** [comment]
Available as of [3.0.0-alpha.10](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.10) 
Feel free to report any bugs. I'll close this feature request issue. 🙂

Enjoy! 👍
Cheers,
Griefed
