### ISSUE TITLE
Feature request: Allow specification of server.properties to include

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#89]
* **What is the current behavior?**

when selecting the **server.properties** to be included, it always includes the default one

* **What is the wanted/requested behavior?**

use previously set **server.properties**

* **What are your reasons for making this feature request? Provide solid arguments on why I should start working on it.**
* 
Now that, we can save and reload configs. It would be nice if it could load the previously set **server.properties** from the conf.

Which means, yet another field to store the absolute path to said **server.properties**, it would pull that one in, if it can't find it, then it would default to the one you're providing?

# ps. add this feature per your request
all i did was replaced "server-icon" with "server.properties"

should be noted that I've not actually cared much about server.properties, altho one advantage might be the setting of some values in it such as level-type.

**Comment by Griefed** [comment]
Will be available in the next alpha release.

**Comment by Griefed** [comment]
https://git.griefed.de/Griefed/ServerPackCreator/-/commit/e3670e4ffc15505856ae9695f59f3c614e0199dd

**Comment by Griefed** [comment]
Available as of [3.0.0-alpha.10](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.10) 
Feel free to report any bugs. I'll close this feature request issue. 🙂

Enjoy! 👍
Cheers,
Griefed
