### ISSUE TITLE
Feature request: Store loaded configuration file as well as default configuration file

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#90]
# I am not sure if this is a feature or not yet
* **What is the current behavior?**

auto save the conf to the last loaded conf and not just the default conf

* **What is the wanted/requested behavior?**

when I power it up, it remembers the alternate conf that I used, and will auto save to that one when I tell it to build, not just the current conf

* **What are your reasons for making this feature request? Provide solid arguments on why I should start working on it.**
* 
for multiple pack devs such as myself with 61+ packs, 2 more by xmas, this wwould be a beneficial feature.

**Comment by Griefed** [comment]
Just so I understand it correctly:

If you load a config you'd like ServerPackCreator to save said config immediately, overwriting the current `serverpackcreator.conf` which resides in its base directory?

Sure thing, that's easily done. I won't validate that config though. If you tell ServerPackCreator to load a config and it overwrites the one residing in the base directory, it is your responsibility to load a valid configuration.

Currently, the configuration in the base dir is only overwritten if the one you just told it to make a server pack with is a valid configuration. This would be circumvented by loading and immediately saving.

**Comment by Griefed** [comment]
Now im confused :D

If you use the GUI version, the `serverpackcreator.conf`-file present in ServerPackCreators directory gets loaded. This config is either:
* A configuration generated by a previous, successful, run of ServerPackCreator in GUI mode
* The default one generated by ServerPackCreator, if no `serverpackcreator.conf`-file was found when starting.

The default is only used if no `serverpackcreator.conf`-file was present, hence it is then generated, * then* read into the GUI.

When you run the generation of a server pack in GUI mode, no problems are detected in the configuration set in the GUI, the currently present `serverpackcreator.conf`-file is replaced with the configuration from the GUI.

Which part of that would you like to be changed and how exactly? Sorry for asking, but I currently do not understand what you mean by 
> Then when I goto the build server button, at the time, the both the default config (which I suspect happens already) and the custom config are updated.
> 
> This way when I load one of my previously worked on configs everything in it will be as according to the last changes.

**Comment by Griefed** [comment]
Will be available in the next alpha release. See https://git.griefed.de/Griefed/ServerPackCreator/-/commit/e03b8089dca9ca40aa8d2a07948603888fbefd70

Saves the last loaded configuration alongside the default serverpackcreator.conf, unless a new configuration was started. Can be activated/deactivated with `de.griefed.serverpackcreator.configuration.saveloadedconfig=true` or `false` respectively

**Comment by Griefed** [comment]
Available as of [3.0.0-alpha.10](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.10) 
Feel free to report any bugs. I'll close this feature request issue. 🙂

Enjoy! 👍
Cheers,
Griefed
