### ISSUE TITLE
Feature request: Reset fields in GUI to start with a fresh new configuration

### ISSUE THREAD

**Issue by kreezxil** [Griefed/ServerPackCreator#91]
* **What is the current behavior?**

No way to reset the data to blank.

* **What is the wanted/requested behavior?**

Set the data to blank with File->New Configuration

* **What are your reasons for making this feature request? Provide solid arguments on why I should start working on it.** 
 
To not have to delete all the fields when starting on a fresh configuration.

**Comment by Griefed** [comment]
Good one.
It's a hassle to manually delete the `serverpackcreator.conf` which gets loaded at the start, so having a `New Configuration`-button in the `File`-menu in the menubar makes sense.

**Comment by Griefed** [comment]
Will be available in the next alpha release

**Comment by Griefed** [comment]
https://git.griefed.de/Griefed/ServerPackCreator/-/commit/dddee0286ca110bb25c75ff5d66756e86130b356

**Comment by Griefed** [comment]
Available as of [3.0.0-alpha.10](https://github.com/Griefed/ServerPackCreator/releases/tag/3.0.0-alpha.10) 
Feel free to report any bugs. I'll close this feature request issue. 🙂

Enjoy! 👍
Cheers,
Griefed
